[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Welchem nicht-asynchronen Trait der Rust-Standardbibliothek ist der Trait `Stream` am ähnlichsten?
"""
prompt.distractors = ["`Write`", "`Index`", "`Sync`"]
answer.answer = "`Iterator`"
context = """
Der Trait `Stream` stellt eine asynchrone Version eines Rust-Iterators bereit.
"""
id = "f94a87f0-a4d6-4cd6-bcee-dfcc606f8ec2"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du hast einen Stream, der die Folge `["A", "B", "C"]` erzeugt, und einen weiteren Stream, der die Folge ["D", "E", "F"] erzeugt.
Du weißt nicht, wann jeder Stream welches Zeichen ausgibt, nur dass es in den angegebenen Folgen geschieht.
Stell dir vor, du führst diese Streams zusammen und gibst jedes Zeichen aus. Wähle dann alle der folgenden Ausgaben aus, die ausgegeben werden könnten.
"""
prompt.distractors = [
  "ACBDEF",
  "CFBEAD"
]
answer.answer = [
  "ABDEFC",
  "DEFABC"
]
context = """
Das Zusammenführen hält immer die Reihenfolge innerhalb jedes Streams ein, sodass z. B. „B“ nicht vor „C“ vorkommen kann.
"""
id = "84452eff-13df-4fcb-91ea-1f504d5bfaf0"
