[[questions]]
type = "MultipleChoice"
prompt.prompt = "Welche der folgenden Aussagen beschreibt bei einem gegebenen Future `f` am besten, wie `f.await` funktioniert?"
prompt.distractors = [
  "Es ruft `f.poll()` einmal auf, was an Ort und Stelle blockiert, bis `f` fertig ist",
  "Es ruft `f.poll()` in einer Schleife auf und beendet sie, wenn `f` fertig ist, oder pollt sofort erneut, wenn `f` nicht fertig ist",
  "Es ruft `f.push(...)` einmal auf, was einen Callback mit dem restlichen Code nach `f.await` ausführt, sobald `f` fertig ist"
]
answer.answer = "Es ruft `f.poll()` in einer Schleife auf und beendet sie, wenn `f` fertig ist, oder gibt die Kontrolle an die Async-Runtime zurück, wenn `f` nicht fertig ist"
context = """
Rust verwendet für die Ausführung von Futures ein Modell, das auf Polling basiert. Ein Await-Punkt wird zu einer Schleife aufgelöst, die wiederholt `.poll()` aufruft
und nach jedem erfolglosen Poll die Kontrolle an die Async-Runtime abgibt, damit anderer asynchroner Code laufen kann. Die Runtime kann den Code von `f.await` später
„aufwecken“, damit er `f` erneut pollt.
"""
id = "c4d90f3c-7286-4272-921c-241b266e9f91"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Stell dir vor, Rust würde nicht verlangen, dass Futures fixiert sind, um gepollt zu werden.
Welche der folgenden async-Funktionen könnte ohne Fixieren potenziell undefiniertes Verhalten verursachen?
"""
prompt.distractors = [
"""
```rust
async fn example(x: &i32) -> i32 {
    sleep(Duration::from_secs(1)).await;
    *y
}
```
""",
"""
```rust
async fn example(x: Vec<i32>) -> i32 {
    sleep(Duration::from_secs(1)).await;
    x[0]
}
```
""",
"""
```rust
async fn example() -> i32 {
    let x = 0;
    sleep(Duration::from_secs(1)).await;
    x
}
```
""",  
]
answer.answer = """
```rust
async fn example(x: i32) -> i32 {
    let y = &x;
    sleep(Duration::from_secs(1)).await;
    *y
}
```
"""
context = """
Das Kernproblem, das das Fixieren löst, ist Selbstreferenz, also ein Future, das einen Zeiger auf sich selbst enthält.
Das passiert, wenn ein async-Block eine lokale Variable enthält, die auf eine andere lokale Variable im Future verweist.
Hier wäre das `y = &x`.
"""
id = "bc8b4acb-d111-4fec-b89a-e5d1bc77c8f2"
