[[questions]]
type = "MultipleChoice"
prompt.prompt = "Was solltest du tun, wenn du in nicht asynchronem Code auf ein Future warten willst?"
prompt.distractors = [
  "Ein `.await` direkt hinter das Future setzen",
  "Das Future an die eingebaute Async-Runtime von Rust übergeben",
  "Das Future in einen `async`-Block verpacken und den Block mit `.await` abwarten",  
]
answer.answer = "Das Future an eine Async-Runtime eines Drittanbieters übergeben" 
context = """
Rust erlaubt `.await` nicht außerhalb von `async`-Blöcken oder -Funktionen. Rust hat auch keine eingebaute Async-Runtime.
Du solltest eine Async-Runtime eines Drittanbieters wie `tokio` oder `trpl` verwenden. 
"""
id = "de2a5023-dd5c-412e-8425-c8ed638f18f0"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
In welche Typsignatur wird die folgende async-Funktion aufgelöst (ohne syntaktischen Zucker)?

```rust
async fn calculate(nums: &[i32]) -> i32 {
  /* ... */
}
```
"""
prompt.distractors = [
  """
```rust
fn calculate<'a>(nums: &'a [i32], output: &mut impl Future<Output = i32> + 'a);
```
  """,
  """
```rust
fn calculate(nums: &'_ [i32]) -> i32 as Future;
```
  """,
  """
```rust
fn calculate() -> impl for<'a> Future<Input = &'a [i32], Output = i32> + 'a;
```
  """
]
answer.answer = """
```rust
fn calculate<'a>(nums: &'a [i32]) -> impl Future<Output = i32> + 'a;
```
"""
context = """
Eine async-Funktion gibt einen anonymen Typ zurück, der den Trait `Future` implementiert und dessen Ausgabe der Rückgabetyp der Funktion ist. 
Hier wird das also als `impl Future<Output = i32>` dargestellt. Das Future erfasst alle Lifetimes in den Argumenten der Funktion.
Daher hat der zurückgegebene Typ den Bound `+ 'a`, und der Eingabe-Slice hat den Typ `&'a [i32]`. Das zeigt an, dass der Slice 
mindestens so lange leben muss wie das Future, das ihn erfasst.
"""
id = "9c000322-464b-4d34-9e30-55591f9283d2"
