[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Betrachte folgende Funktion:

```rust
async fn print_letters() {
  let a = async { print!("A"); };
  let b = async { print!("B"); };
  let c = async { print!("C"); };
  c.await;
  b.await;
  a.await;
}
```

Welche der folgenden Strings können möglicherweise ausgegeben werden, nachdem `print_letters().await` ausgeführt wurde?
"""
prompt.distractors = ["`ABC`", "`BCA`", "`ACB`"]
answer.answer = ["`CBA`"]
context = """
Dieses Programm verhält sich deterministisch. Die Ausgaben werden erst ausgeführt, wenn die async-Blöcke abgewartet werden.
Die Blöcke werden in der Reihenfolge `c`/`b`/`a` abgewartet, daher gibt das Programm nur `CBA` aus.
"""
id = "8f62c158-525a-43a2-aa6a-0cc106cada10"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du hast eine Hilfsfunktion `wait_all(a, b)` mit folgendem Verhalten:
* `wait_all` garantiert, dass `a` und `b` vollständig ausgeführt werden.
* `wait_all` gibt keine Garantien hinsichtlich Fairness oder anfänglicher Ausführungsreihenfolge.

Gegeben ist dann folgender Code:

```rust
async fn print_letters() {
  let fut1 = async { 
    print!("A");
    sleep().await;
    print!("B");
  };
  let fut2 = async {
    print!("C");
    sleep().await;
    print!("D");
  }
  wait_all(fut1, fut2).await;
}
```

Welche der folgenden Strings können möglicherweise ausgegeben werden, nachdem `print_letters().await` ausgeführt wurde?
"""
prompt.distractors = ["`DABC`"]
answer.answer = [
  "`ABCD`", "`CADB`", "`ACBD`"
]
context = """
Das hypothetische Primitiv `wait_all` ist wie `join`, aber mit weniger Garantien. Mit nur der Spezifikation in dieser Aufgabe ist jede Verschränkung der
beiden Futures gültig. Die einzige ungültige Ausgabe ist eine, die die Ausführungsreihenfolge im Programm umkehrt, also `DABC`, bei der `D` vor `C` ausgegeben würde.
"""
id = "4b28f13e-9781-4d29-b886-7639fa527f36"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du hast einen Kanal zur Nachrichtenübermittlung `channel()`, der nicht blockierend und *begrenzt* ist, 
d. h., `send` gibt ein Future zurück, das fertig ist, sobald im Kanal Kapazität frei ist.
Angenommen, du hast außerdem eine Funktion `join(a, b)`, die *fair* darauf wartet, dass beide Argumente fertig sind. Gegeben ist dann dieser asynchrone Code:

```rust
let (tx, mut rx) = channel(16);
let recv_fut = rx.recv();
let send_fut = tx.send(0);
let (n, _) = join(recv_fut, send_fut).await;
println!("{}", n.unwrap());
```

Was passiert, wenn dieser Code ausgeführt wird?
"""
prompt.distractors = [
  "Das Programm gibt `0` aus und läuft endlos weiter",
  "Das Programm gibt nichts aus und läuft endlos weiter",
  "Das Programm löst einen Panic aus"
]
answer.answer = "Das Programm gibt `0` aus und beendet sich"
context = """
Da der Kanal nicht blockiert, können wir vor dem Senden ein Empfangs-Future erzeugen, ohne in eine Endlosschleife zu geraten.
"""
id = "e23b7c48-3780-44e7-8ea4-df35032548a1"
