[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Gegeben ist eine Funktion `sleep(d)`, die für die angegebene Dauer schläft. Betrachte diese Funktion:

```rust
let futs: Vec<_> = [1, 2, 3].iter().map(|n| async move {
  sleep(Duration::from_secs(5)).await;
  n + 1
}).collect();

for fut in futs {
  let n = fut.await;
  println!("{n}");
}
```

Wie viele Sekunden sollte die Ausführung ungefähr dauern?
"""
prompt.distractors = ["5", "0"]
answer.answer = "15"
context = """
Ohne eine Funktion wie `join_all` laufen die Futures nicht nebenläufig. Daher würde dieser Code 15 Sekunden dauern (5 Sekunden pro Listenelement).
"""
id = "68680e2e-7a9f-4cee-8080-70e57fe5a2b3"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du entwirfst eine Hilfsfunktion mit folgender Spezifikation:

> `map_stringify` nimmt zwei Argumente: einen Vektor von Eingaben und eine async-Funktion, die die Eingabe in eine Ausgabe umwandelt,
> wobei sich die Ausgaben in Strings umwandeln lassen.
> `map_stringify` gibt einen Vektor der in Strings umgewandelten Ausgaben zurück.

Welche Typsignatur einer Funktion bildet diese Spezifikation am besten ab?
"""
prompt.distractors = [
"""
```rust
async fn map_stringify(
  inputs: Vec<String>, f: impl Future<Output = String>
) -> Vec<String>
```
""",
"""
```rust
fn map_stringify<I, O, F>(
  inputs: Vec<I>, f: impl Fn(I) -> O,
) -> Vec<impl Future<Output = String>>
where
  O: ToString,  
```
""",
"""
```rust
async fn map_stringify<I, F>(
  inputs: Vec<I>, f: impl Fn(I) -> F, 
) -> Vec<String>
where
  F: Future + ToString,
```
"""]
answer.answer = """
```rust
async fn map_stringify<I, O, F>(
  inputs: Vec<I>, f: impl Fn(I) -> F, 
) -> Vec<String>
where
  O: ToString,
  F: Future<Output = O>,
```
"""
context = """
Hier ist eine Implementierung der spezifizierten Funktion:

```rust
async fn map_stringify<I, O, F>(
  f: impl Fn(I) -> F, inputs: Vec<I>
) -> Vec<String>
where
  O: ToString,
  F: Future<Output = O>,
{
  let f = &f;
  let futs = inputs
    .into_iter()
    .map(|input| async move { f(input).await.to_string() });
  futures::future::join_all(futs).await
}
```
"""
id = "b42a9c5b-bfe7-4d6f-967a-f8ff2a6faa0d"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du schreibst ein Programm, das asynchronen Code ausführen, aber alle 500 ms prüfen muss, ob die Berechnung angehalten werden soll.
Welche Hilfsfunktion wäre für diese Aufgabe am besten geeignet?
"""
prompt.distractors = [
  "`join`",
  "`yield`",
  "`spawn` / `spawn_task`"
]
answer.answer = "`race` / `select`"
context = """
Du könntest zum Beispiel in einer Schleife ein `select` zwischen einem langwierigen Future und einem Schlaf-Future ausführen, das nach 500 ms fertig ist.
"""
id = "7da21e95-8e03-412b-8c4d-90ccfc8c6802"
