[[questions]]
id = "87c3b09e-84d3-49d7-8680-0b2d068a7fc5"
type = "ShortAnswer"
prompt.prompt = "Jedes ausführbare Rust-Programm muss eine Funktion mit folgendem Namen enthalten:"
answer.answer = "main"
context = """
In deinem Programm fügst du eine main-Funktion so hinzu:

```
fn main() {
  // your code here
}
```
"""

[[questions]]
id = "0d78d302-eb3d-4ac7-a1ac-f2d661810744"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du hast folgendes Programm in einer Datei `hello.rs`:

```
fn main() {
  println!("Hello world!");
}
```

Angenommen, du führst dann auf der Kommandozeile den Befehl `rustc hello.rs` aus. Welche Aussage beschreibt am besten, was als Nächstes passiert?
"""
answer.answer = "`rustc` erzeugt eine ausführbare Binärdatei namens `hello`"
prompt.distractors = [
  "`rustc` gibt einen Fehler aus, weil das Programm ungültig ist",
  "`rustc` führt das Programm aus und gibt `Hello world!` aus",
  "`rustc` formatiert `hello.rs` gemäß dem Rust-Styleguide neu"
]
context = """
`rustc` prüft und kompiliert dein Programm, führt es aber nicht aus.
"""