[[questions]]
id = "c1b7cc2e-b5fb-4b67-b0bb-600d82931f08"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du hast gerade ein Cargo-Projekt heruntergeladen und führst dann auf der Kommandozeile `cargo run` aus. Welche Aussage über das, was als Nächstes passiert, ist NICHT wahr?
"""
answer.answer = "Cargo überwacht Dateiänderungen und führt die Binärdatei bei einer Änderung erneut aus"
prompt.distractors = [
  "Cargo lädt alle Abhängigkeiten des Projekts herunter und baut sie",
  "Cargo baut das Projekt zu einer Binärdatei im Verzeichnis `target/debug`",
  "Cargo führt die Binärdatei des Projekts aus"
]
context = """
Cargo überwacht deine Dateien standardmäßig nicht. Dafür kannst du aber Plugins wie [cargo-watch](https://crates.io/crates/cargo-watch)
verwenden.
"""