[[questions]]
id = "6286342a-84c1-47c5-bfd2-f34b51df813c"
type = "ShortAnswer"
prompt.prompt = "Wie heißt das Kommandozeilenwerkzeug, mit dem du die Rust-Version auf deinem Rechner verwaltest?"
answer.answer = "rustup"
context = """
Mit `rustup update` bekommst du zum Beispiel die neueste Version von Rust.
"""
