[[questions]]
id = "8e2d2cd0-48d4-4901-a8c5-c994fb318014"
type = "ShortAnswer"
prompt.prompt = "Das Schlüsselwort zum Deklarieren einer neuen Funktion in Rust lautet:"
answer.answer = "fn"

[[questions]]
id = "bbcac2a0-dec8-4b3b-88fd-37880e804259"
type = "Tracing"
prompt.program = """
fn f(x) { 
  println!("{x}");
}

fn main() {
  f(0);
}
"""
answer.doesCompile = false
answer.lineNumber = 1
context = """
Eine Funktion muss die Typen ihrer Parameter deklarieren.
"""
