[[questions]]
id = "dca33d34-6294-43f4-9267-fd62d7dce993"
type = "Tracing"
prompt.program = """
fn main() {
  let mut x: u32 = 1;
  {
    let mut x = x;
    x += 2;
  }
  println!("{x}");
}
"""
answer.doesCompile = true
answer.stdout = "1"
context = """
Die Anweisung `x += 2` betrifft nur das überschattende `x` innerhalb der inneren geschweiften Klammern, nicht das äußere `x` in Zeile 2.
"""

[[questions]]
id = "15b9d091-3b09-49fe-a472-ba6c0f69e4e0"
type = "Tracing"
prompt.program = """
fn main() {
  let mut x: u32 = 1;
  x = "Hello world";
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
Einer Variable kann kein Wert zugewiesen werden, dessen Typ sich von ihrem ursprünglichen Typ unterscheidet.
"""
