[[questions]]
id = "a48e524e-852c-400c-ae68-5c76a6761596"
type = "MultipleChoice"
prompt.prompt = "Welche der folgenden Aussagen über den Unterschied zwischen `let` und `const` beim Deklarieren einer Variable ist richtig?"
answer.answer = "`const` kann im globalen Gültigkeitsbereich verwendet werden, `let` nur innerhalb einer Funktion"
prompt.distractors = [
  "Beides sind nur verschiedene Syntaxformen, um Variablen mit derselben Semantik zu deklarieren",
  "Der Compiler meldet einen Fehler, wenn der Name einer `const`-Variable nicht in `UPPER_SNAKE_CASE` geschrieben ist",
  "Einer `const` kann nur ein Literal zugewiesen werden, kein Ausdruck, der etwas berechnet"
]

[[questions]]
id = "d209784f-cc52-4451-8049-ad204e89d587"
type = "Tracing"
prompt.program = """
const TWO: u32 = 1 + 1;
fn main() {
  println!("{TWO}");
}
"""
answer.doesCompile = true
answer.stdout = "2"
context = """
`const`-Variablen dürfen außerhalb einer Funktion definiert werden und eingeschränkte Formen von Berechnungen enthalten.
"""