[[questions]]
id = "8bd8d8bc-e61e-48c7-ba78-0c89339e5995"
type = "MultipleChoice"
prompt.prompt = "Welche Aussage beschreibt am besten, was es bedeutet, wenn eine Variable `x` unveränderlich ist?"
answer.answer = "`x` kann nicht mehr geändert werden, nachdem ihr ein Wert zugewiesen wurde."
prompt.distractors = [
  "`x` wird im unveränderlichen Bereich des Speichers abgelegt.",
  "Nach der Definition kann `x` höchstens einmal geändert werden.",
  "Man kann keine Referenz auf `x` erzeugen."
]
context = """
Unveränderlich (*immutable*) heißt „nicht veränderlich“, also nicht änderbar.
"""

[[questions]]
id = "dcf53c67-b3c9-4c54-8da0-90749cc669e8"
type = "ShortAnswer"
prompt.prompt = "Welches Schlüsselwort steht nach `let`, um anzuzeigen, dass eine Variable verändert werden kann?"
answer.answer = "mut"
context = """
Eine veränderliche Variable `x` erzeugst du zum Beispiel so: `let mut x = 1`.
"""

[[questions]]
id = "77f9f143-45a6-4f08-bd87-72bc50c00693"
type = "Tracing"
prompt.program = """
fn main() {
  let x = 1;
  println!("{x}");
  x += 1;
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
Das ist ein Compilerfehler, weil Zeile 4 versucht, `x` zu verändern, obwohl `x` nicht als `mut` markiert ist.
"""