[[questions]]
id = "30212501-00d5-4ef6-838f-3df5112ee7ed"
type = "Tracing"
prompt.program = """
fn main() {
  let message = "The temperature today is:";
  let x = [message, 100];
  println!("{} {}", x[0], x[1]);
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
Ein Array kann nur Elemente eines einzigen Typs enthalten. Die Syntax `[message, 100]` erzeugt ein Array mit zwei Elementen.
Die Variable `message` ist ein String, die Konstante `100` dagegen eine Zahl.
"""

[[questions]]
id = "4e632a23-24cc-4c29-8935-cf6b62c3764b"
type = "Tracing"
prompt.program = """
fn main() {
  let t = ([1; 2], [3; 4]);
  let (a, b) = t;
  println!("{}", a[0] + t.1[0]); 
}
"""
answer.doesCompile = true
answer.stdout = "4"
context = """
Die Syntax `[x; y]` deklariert ein Array mit `y` Kopien des Werts `x`. Die Syntax `(a, b)` destrukturiert `t` und bindet `a` an `[1; 2]`. 
Die Syntax `t.1` bezeichnet das zweite Element von `t`, also `[3; 4]`.
"""