[[questions]]
id = "e582f00a-2f28-46e4-ae1b-77fd223cca4f"
type = "MultipleChoice"
prompt.prompt = "Die größte Zahl, die mit dem Typ `i128` darstellbar ist, lautet:"
answer.answer = "2<sup>127</sup> - 1"
prompt.distractors = [
  "2<sup>128</sup>",
  "2<sup>128</sup> - 1",
  "2<sup>127</sup>",
]
prompt.answerIndex = 3
context = """
Allgemein kann eine vorzeichenbehaftete Zahl mit *n* Bits Zahlen zwischen -(2<sup>n - 1</sup>) und 2<sup>n - 1</sup> - 1 darstellen.
"""

[[questions]]
id = "3a92246b-a43c-4658-980b-335d7632ddcb"
type = "MultipleChoice"
prompt.prompt = "Was passiert bei der Berechnung von `x - 1`, wenn `x : u8 = 0` gilt?"
answer.answer = "Das hängt vom Compiler-Modus ab." 
prompt.distractors = [
  "Es löst immer einen Panic aus.",
  "Es gibt immer 255 zurück.",
]
context = """
Dieser Ausdruck löst im Debug-Modus einen Panic aus und gibt im Release-Modus 255 zurück.
"""

[[questions]]
id = "9bcac1a1-d2df-4a51-b399-7fd8a6042cc2"
type = "Tracing"
prompt.program = """
fn main() {
  let x: fsize = 2.0;
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 2
context = """
Den Typ `fsize` gibt es nicht. Gleitkommazahlen sind entweder `f32` oder `f64`.
"""