[[questions]]
id = "7fbda6e4-dca7-458e-ab52-fab03181f90b"
type = "MultipleChoice"
prompt.prompt = """
Betrachte die Variablen `s2` und `s3` im folgenden Programm. Diese beiden Variablen liegen im Speicher innerhalb des Stack-Frames von `main`. Jede Variable hat eine Größe im Speicher auf dem Stack, *ohne* die Größe der Daten, auf die sie zeigt. Welche Aussage über die Größen von `s2` und `s3` ist wahr?

```
fn main() {
  let s = String::from("hello");
  let s2: &String = &s;
  let s3: &str = &s[..];
}
```
"""
answer.answer = "`s3` belegt mehr Bytes als `s2`"
prompt.distractors = [
  "`s3` belegt genauso viele Bytes wie `s2`",
  "`s3` belegt weniger Bytes als `s2`"
]
context = """
Der Typ `&String` ist eine normale Referenz, die aus einem einzigen Zeiger besteht, also auf einer 64-Bit-Architektur 8 Bytes groß ist. Der Typ `&str` ist eine besondere Slice-Referenz, die aus einem Zeiger *und* einer Länge besteht, also 16 Bytes. Deshalb belegt `s3` vom Typ `&str` mehr Speicher als `s2` vom Typ `&String`. Du kannst das selbst mit [`std::mem::size_of`](https://doc.rust-lang.org/std/mem/fn.size_of.html) überprüfen, etwa so:

```rust
fn main() {
  println!(
    "&String={} &str={}",
    std::mem::size_of::<&String>(),
    std::mem::size_of::<&str>(),
  );
}
```

Beachte außerdem, dass Rust String-Referenzen je nach Kontext der Referenz implizit entweder in `&String` oder in `&str` umwandelt. Der Ausdruck `&s` erzeugt also je nach erwartetem Typ von `&s` zwei verschiedene Werte.
"""

[[questions]]
id = "adcfc154-03bd-470a-bacb-b3cad97cfc7f"
type = "Tracing"
prompt.program = """
fn main() {
  let mut s = String::from("hello");
  for &item in s.as_bytes().iter() {
    if item == b'l' {
      s.push_str(" world");
    }
  }
  println!("{s}");
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """
Weil `s.as_bytes()` eine unveränderliche Referenz auf `s` erzeugt, ist es nicht erlaubt, `s` innerhalb der for-Schleife (über `push_str`) zu verändern.
"""