[[questions]]
id = "8c9f9173-c5ba-4914-9cfa-e3432f8414e1"
type = "MultipleChoice"
prompt.prompt = """
Welche der folgenden Möglichkeiten ist KEINE gültige Lösung für das Problem, eine Referenz auf den Stack aus einer Funktion zurückzugeben?
"""
answer.answer = "Die Lifetime des Stack-Frames verlängern"
prompt.distractors = ["Einen Zeiger mit Referenzzählung verwenden", "Die Ownership des zurückgegebenen Werts übernehmen", "Von der aufrufenden Stelle einen veränderlichen Platz erwarten"]
context = """
Die Lifetime eines Stack-Frames lässt sich nicht verlängern, daher ist das keine gültige Lösung.
"""

[[questions]]
id = "e6bc84ef-069c-4d1d-99ec-69b13492569c"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, jemand hat versucht, folgende Funktion zu schreiben:

```
/// Returns a person's name with "Ph.D." added as a title
fn award_phd(name: &String) -> String {
    let mut name = *name;
    name.push_str(", Ph.D.");
    name
}
```

Der Rust-Compiler weist den Code mit folgendem Fehler zurück:

```text
error[E0507]: cannot move out of `*name` which is behind a shared reference
 --> test.rs:3:20
  |
3 |     let mut name = *name;
  |                    ^^^^^
  |                    |
  |                    move occurs because `*name` has type `String`, which does not implement the `Copy` trait
  |                    help: consider borrowing here: `&*name`
```

Welche der folgenden Korrekturen wäre angesichts des angegebenen Zwecks der Funktion die idiomatischste? 
Die Unterschiede zur obigen Funktion sind hervorgehoben.
"""
answer.answer = """
```
fn award_phd(name: &String) -> String {
    let mut name = `[name.clone()]`;
    name.push_str(", Ph.D.");
    name
}
```
"""
prompt.distractors = [
"""
```
fn award_phd(name: &String) -> String {
    let mut name = `[&*name]`;
    name.push_str(", Ph.D.");
    name
}
```
""",
"""
```
fn award_phd(`[mut name: String]`) -> String {
    name.push_str(", Ph.D.");
    name
}
```
""",
"""
```
fn award_phd(`[name: &mut String]`) {
    name.push_str(", Ph.D.");
}
```
"""
]
context = """
Die Funktion soll den ursprünglichen Namen einer Person nicht ändern, daher wäre es unpassend, den Typ von `name` in `&mut String` oder `String` 
zu ändern. Die vom Compiler vorgeschlagene Lösung `&*name` reicht nicht aus – eine akzeptable Lösung ist, 
die Daten mit `name.clone()` zu klonen und die lokale Kopie zu verändern.
"""

[[questions]]
id = "8020e4a2-f0b4-4eae-90ac-a87712d9d00b"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, jemand hat versucht, folgende Funktion zu schreiben:

```
/// Rounds all the floats in a vector to the nearest integer, in-place
fn round_in_place(v: &Vec<f32>) {
    for n in v {
        *n = n.round();
    }
}
```

Der Rust-Compiler weist den Code mit folgendem Fehler zurück:

```text
error[E0594]: cannot assign to `*n`, which is behind a `&` reference
 --> test.rs:4:9
  |
3 |     for n in v {
  |              - this iterator yields `&` references
4 |         *n = n.round();
  |         ^^^^^^^^^^^^^^ `n` is a `&` reference, so the data it refers to cannot be written
```

Welche der folgenden Korrekturen wäre angesichts des angegebenen Zwecks der Funktion die idiomatischste? 
Die Unterschiede zur obigen Funktion sind hervorgehoben.
"""
answer.answer = """
```
fn round_in_place(v: `[&mut Vec<f32>]`) {
    for n in v {
        *n = n.round();
    }
}
```
"""
prompt.distractors = [
"""
```
fn round_in_place(v: &Vec<f32>) `[-> Vec<f32>]` {
    `[let mut v2 = Vec::new();]`
    for n in v {
        `[v2.push(n.round());]`
    }
    `[v2]`
}
```
""",
"""
```
fn round_in_place(`[mut v: Vec<f32>]`) {
    for n in v {
        *n = n.round();
    }    
}
```
""",
"""
```
fn round_in_place(v: &Vec<f32>) {
    for `[mut n]` in `[&mut v.clone()]` {
        n = n.round();
    }    
}
```
""",
]
context = """
Weil diese Funktion einen Vektor direkt an Ort und Stelle runden soll, wäre es nicht
idiomatisch, eine neue Kopie desselben Vektors zurückzugeben (`-> Vec<f32>`) oder die
Ownership des Vektors zu übernehmen (`mut v: Vec<f32>`). Die beste Lösung ist, 
die Typsignatur von `&Vec<f32>` in `&mut Vec<f32>` zu ändern.
"""
