[[questions]]
id = "5080616f-6f4c-43f7-aa3a-8b23f2798937"
type = "Tracing"
prompt.program = """
fn incr(n: &mut i32) {
  *n += 1;
}

fn main() {
  let mut n = 1;
  incr(&n);
  println!("{n}");
}
"""
answer.doesCompile = false
answer.lineNumber = 7
context = """
Obwohl `n` als `mut` markiert ist, muss auch die Referenz auf `n` als `mut` markiert sein.
Eine gültige Version dieses Programms würde also `incr(&mut n)` schreiben.
"""


[[questions]]
id = "e9846c5d-1254-4420-9986-dae4af86b9af"
type = "Tracing"
prompt.program = """
fn main() {
  let mut s = String::from("hello");
  let s2 = &s;
  let s3 = &mut s;
  s3.push_str(" world");
  println!("{s2}");
}
"""
answer.doesCompile = false
answer.lineNumber = 6
context = """
Es ist nicht erlaubt, eine veränderliche Referenz auf einen Wert (`s3`) zu verwenden, während eine unveränderliche Referenz
lebendig ist (`s2`).
"""

[[questions]]
id = "80f6bcd6-b74a-4da3-a014-d423c82ce405"
type = "MultipleChoice"
prompt.prompt = """
Betrachte diese Rust-Funktion, die eine Zahl ans Ende eines Vektors anfügt und dann die Zahl am Anfang des Vektors entfernt und zurückgibt:

```
fn give_and_take(v: &Vec<i32>, n: i32) -> i32 {
    v.push(n);
    v.remove(0)
}
```

Wenn du versuchst, diese Funktion zu kompilieren, gibt der Compiler normalerweise folgenden Fehler aus:

```text
error[E0596]: cannot borrow `*v` as mutable, as it is behind a `&` reference
 --> test.rs:2:5
  |
1 | fn give_and_take(v: &Vec<i32>, n: i32) -> i32 {
  |                     --------- help: consider changing this to be a mutable reference: `&mut Vec<i32>`
2 |     v.push(n);
  |     ^^^^^^^^^ `v` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```

Nimm an, der Compiler würde diese Funktion NICHT zurückweisen. Wähle alle (falls vorhanden) der folgenden Programme aus, die bei der Ausführung
undefiniertes Verhalten verursachen könnten. Wenn keines dieser Programme undefiniertes Verhalten verursachen könnte,
wähle „Keines dieser Programme“.
"""
answer.answer = [
"""
```
let v = vec![1, 2, 3];
let n = &v[0];
give_and_take(&v, 4);
println!("{}", n);
```
""",
]
prompt.distractors = [
"""
```
let v = vec![1, 2, 3];
let v2 = &v;
give_and_take(&v, 4);
println!("{}", v2[0]);
```
""",
"""
```
let v = vec![1, 2, 3];
let n = &v[0];
let k = give_and_take(&v, 4);
println!("{}", k);
```
""",
"Keines dieser Programme"
]
context = """
Wie wir weiter oben in diesem Abschnitt gesehen haben, kann `v.push(n)` dazu führen, dass `v` seinen internen Inhalt neu alloziert, wodurch alle Referenzen auf die Elemente von `v` auf dem Heap ungültig werden.
Der Aufruf `give_and_take(&v, 4)` führt deshalb dazu, dass zuvor erzeugte Referenzen auf Elemente auf ungültigen Speicher zeigen. Die beiden Programme, die `let n = &v[0]`
vor `give_and_take` binden, sind Kandidaten für undefiniertes Verhalten. `let v2 = &v` ist kein Kandidat, weil eine Referenz auf den Container `v` durch das Verändern von `v`
nicht tatsächlich ungültig wird.

Das Programm mit `println!(\"{}\", n)` verursacht undefiniertes Verhalten, weil es den ungültigen Speicher liest. Das Programm mit `println!(\"{}\", k)` verursacht kein undefiniertes
Verhalten, weil es die ungültig gewordene Referenz nicht verwendet.
"""