[[questions]]
id = "1ec0098c-c5dc-46de-a889-b6659c0af757"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du schreibst eine Funktion mit folgender Spezifikation:

> `round_all` nimmt eine Liste von Gleitkommazahlen als Eingabe und rundet jede Zahl an Ort und Stelle auf die nächste Ganzzahl.

Welche der folgenden Typsignaturen passt am besten für eine Funktion, die diese Spezifikation umsetzt?
"""
answer.answer = """
```
fn round_all(v: &mut Vec<f32>);
```
"""
prompt.distractors = [
"""
```
fn round_all(v: &Vec<f32>) -> Vec<f32>;
```
""",
"""
```
fn round_all(v: Vec<f32>);
```
""",
"""
```
fn round_all(v: &Vec<f32>);
```
"""
]
context = """
Die Spezifikation verlangt, dass die Eingabe an Ort und Stelle verändert wird; die passendste Typsignatur nimmt daher eine veränderliche Referenz auf die Eingabe.
Eine unveränderliche Referenz oder ein Vektor mit Ownership passen beide nicht zu dieser Spezifikation.
"""

[[questions]]
id = "f8ca5ab2-0e5d-4c0d-bca2-99e6763ba9c5"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du schreibst eine Funktion mit folgender Spezifikation:

> `find_contains` nimmt eine Collection von Strings und einen gesuchten Teilstring als Eingabe. 
> Sie gibt eine Liste aller Strings in der Collection zurück, die den gesuchten Teilstring enthalten.

Welche der folgenden Typsignaturen passt am besten für eine Funktion, die diese Spezifikation umsetzt?
"""
answer.answer = """
```
fn find_contains(haystack: &[String], needle: &str) -> Vec<&String>;
```
"""
prompt.distractors = [
"""
```
fn find_contains(haystack: &Vec<String>, needle: String) -> Vec<String>;
```
""",
"""
```
fn find_contains(haystack: &[String], needle: &str) -> Vec<String>;
```
""",
"""
```
fn find_contains(haystack: &Vec<String>, needle: &str) -> &[String];
```
"""
]
context = """
Für `haystack` kann der Slice-Typ `&[String]` mehr Eingaben annehmen als `&Vec<String>`, daher ist er vorzuziehen.
Für `needle` muss der gesuchte Teilstring nicht auf dem Heap alloziert sein, daher ist `&str` gegenüber `String` vorzuziehen.
Als Rückgabetyp ist `Vec<String>` nicht wünschenswert, weil dafür die Eingabe-Strings geklont werden müssten.
`&[String]` ist nicht wünschenswert, weil damit nur eine zusammenhängende Teilfolge der Eingabe zurückgegeben werden kann.
`Vec<&String>` ist am besten, weil nur die Kosten für die Allokation des Vektors anfallen, nicht für die Strings selbst.
"""

[[questions]]
id = "868a4edf-16f0-4191-8aed-835c812b8b25"
type = "MultipleChoice"
prompt.prompt = """
Rust verbietet normalerweise mehrere veränderliche Zugriffe auf dasselbe Array, selbst wenn sich diese Zugriffe nicht überschneiden. 
Diese Funktion lässt sich zum Beispiel nicht kompilieren:

```
fn main() {
  let mut v = vec![0, 1, 2, 3];
  let (r0, r1) = (&mut v[0..2], &mut v[2..4]);
  r0[0] += 1;
  r1[0] += 1;  
}
```

Die Standardbibliothek von Rust hat jedoch eine Funktion `slice::split_at_mut`, die genau das ermöglicht:

```
fn main() {
  let mut v = vec![0, 1, 2, 3];
  let (r0, r1) = v.split_at_mut(2);
  r0[0] += 1;
  r1[0] += 1;  
}
```

Welche der folgenden Aussagen beschreibt am besten, wie sich `split_at_mut` implementieren lässt?
"""
answer.answer = "`split_at_mut` verwendet unsicheren Code, um den Borrow-Checker mit Raw-Pointern zu umgehen"
prompt.distractors = [
"`split_at_mut` ist ein spezielles Compiler-Primitiv, das sich nicht innerhalb der Sprache implementieren lässt",
"`split_at_mut` verwendet unsicheren Code, um die Sicherheitsprüfung veränderlicher Referenzen durch den Borrow-Checker abzuschalten",
"`split_at_mut` ruft eine C-Bibliothek auf, die Rust nicht analysieren kann"
]
context = """
Wie in [Kapitel 4.3, „Ein sicheres Programm reparieren: Verschiedene Array-Elemente verändern“](ch04-03-fixing-ownership-errors.html#fixing-a-safe-program-mutating-different-array-elements) besprochen, werden Funktionen wie `split_at_mut` mit dem Feature `unsafe` implementiert.
Dieses Feature schaltet den Borrow-Checker nicht vollständig ab, sondern ermöglicht die Verwendung bestimmter unsicherer Features wie Raw-Pointer.
"""


[[questions]]
id = "ba32e57a-e5f2-42e4-8cfd-eb265990c690"
type = "MultipleChoice"
prompt.prompt = """
Betrachte die Berechtigungen im folgenden Programm:

```aquascope,permissions,boundaries,stepper
#fn main() {
let s = String::new();
let s_ref = &s;`(focus,paths:*s_ref)`
#println!("{s_ref}");
#}
```

Welche der folgenden Aussagen erklärt am besten, warum `*s_ref` die Berechtigung @Perm{own} (Own, besitzen) nicht hat?
"""
answer.answer = "Ownership erlaubt das Verschieben, und das Herausverschieben aus einer Referenz kann einen Double-Free verursachen"
prompt.distractors = [
  "Ownership erlaubt das Ausleihen, und erneutes Ausleihen von `*s_ref` kann einen Double-Free verursachen",
  "Ownership erlaubt das Verändern, und das Verändern von `*s_ref` kann ein Use-after-free verursachen",
  "Ownership erlaubt das Lesen, und das Lesen von `*s_ref` kann ein Use-after-free verursachen"
]
context = """
Die Berechtigung @Perm{own} steht für die Ownership eines Objekts. Ein Objekt kann nur einen einzigen Owner haben, daher ist es wichtig,
dass Referenzen die Ownership nicht kopierbarer Typen wie `String` nicht übertragen können. Würden zwei Variablen glauben, denselben
String zu besitzen, würden beide versuchen, ihn freizugeben, was einen Double-Free verursacht.
"""

[[questions]]
id = "3a5f5de5-23a9-49fb-bdb4-acc9c3fbb4a6"
type = "MultipleChoice"
prompt.prompt = """
Betrachte die Menge der Rust-Programme, die keinen `unsafe`-Code enthalten. 
Wähle jede der folgenden Aussagen aus, die über die vom Borrow-Checker akzeptierten und zurückgewiesenen Programme wahr ist:
"""
answer.answer = [
  "Der Borrow-Checker weist Programme mit undefiniertem Verhalten immer zurück",
  "Der Borrow-Checker weist manchmal Programme ohne undefiniertes Verhalten zurück",
]
prompt.distractors = [
  "Der Borrow-Checker akzeptiert Programme ohne undefiniertes Verhalten immer",  
  "Der Borrow-Checker akzeptiert manchmal Programme mit undefiniertem Verhalten"
]
context = """
Der Borrow-Checker weist Programme mit undefiniertem Verhalten immer zurück, kann aber manchmal auch Programme ohne undefiniertes Verhalten (d. h. vollkommen sichere Programme) zurückweisen.
Fachlich ausgedrückt ist der Borrow-Checker eine korrekte (*sound*), aber unvollständige (*incomplete*) Analyse.
"""


[[questions]]
id = "208e0e38-a706-4d96-9809-f0e12f574136"
type = "MultipleChoice"
prompt.prompt = """
Die Funktion `extract` wird vom Borrow-Checker zurückgewiesen:

```rust
fn extract(b: &Box<i32>) -> i32 {
    let b2: Box<i32> = *b;
    *b2
}
```

Stell dir vor, der Borrow-Checker würde diese Funktion nicht zurückweisen. 
Bestimme, ob es eine Eingabe gibt, bei der die Funktion undefiniertes Verhalten verursachen würde, wenn sie mit dieser Eingabe ausgeführt wird.
"""
answer.answer = "Diese Funktion KÖNNTE undefiniertes Verhalten verursachen"
prompt.distractors = ["Diese Funktion könnte KEIN undefiniertes Verhalten verursachen"]
context = """
Diese Funktion würde bei jeder Eingabe einen Double-Free verursachen.
"""


[[questions]]
id = "dcfd54f8-7fe6-4483-aefd-ea95ba5b5eb0"
type = "MultipleChoice"
prompt.prompt = """
Die Funktion `transfer_string` wird vom Borrow-Checker zurückgewiesen:

```rust
fn get_first(strs: &mut (String, String)) -> &mut String {
    &mut strs.0
}

fn get_second(strs: &mut (String, String)) -> &mut String {
    &mut strs.1
}

fn transfer_string(strs: &mut (String, String)) {
    let fst = get_first(strs);
    let snd = get_second(strs);
    fst.push_str(snd);
    snd.clear();
}
```

Stell dir vor, der Borrow-Checker würde diese Funktion nicht zurückweisen. 
Bestimme, ob es eine Eingabe gibt, bei der die Funktion undefiniertes Verhalten verursachen würde, wenn sie mit dieser Eingabe ausgeführt wird.
"""
answer.answer = "Diese Funktion könnte KEIN undefiniertes Verhalten verursachen"
prompt.distractors = ["Diese Funktion KÖNNTE undefiniertes Verhalten verursachen"]
context = """
Der Borrow-Checker weist diese Funktion zurück, weil er annimmt, dass `get_first` und `get_second` eine veränderliche
Referenz auf jede der beiden Komponenten des Tupels zurückgeben könnten, sodass `fst` und `snd` möglicherweise auf denselben Wert zeigen. In diesem Programm
sind sie aber immer verschieden, also ist diese Funktion tatsächlich sicher.
"""



