[[questions]]
id = "5d774a01-8604-4386-8d81-498496ccd96c"
type = "MultipleChoice"
prompt.prompt = """
Welche der folgenden Aussagen beschreibt den Unterschied zwischen Stack und Heap am besten?
"""
answer.answer = "Der Stack enthält Daten, die zu einer bestimmten Funktion gehören, der Heap dagegen Daten, die eine Funktion überleben können"
prompt.distractors = [ 
  "Der Stack kann Zeiger auf Daten im Heap enthalten, der Heap dagegen nur Daten ohne Zeiger",
  "Der Stack enthält unveränderliche Daten, der Heap dagegen veränderliche Daten.",
  "Der Stack enthält kopierbare Daten, der Heap dagegen nicht kopierbare Daten."
]
context = """
Frames auf dem Stack gehören zu einer bestimmten Funktion und werden freigegeben, wenn die Funktion zurückkehrt.
Daten auf dem Heap können unbegrenzt lange leben. Beachte, dass Daten sowohl auf dem Stack als auch auf dem Heap veränderlich und kopierbar sein können. Der Heap darf
Zeiger enthalten (sogar auf den Stack, wie wir später sehen werden).
"""

[[questions]]
id = "4c953b2d-65bf-4dab-bbbb-14c9b15a690e"
type = "ShortAnswer"
prompt.prompt = """
Betrachte die Ausführung des folgenden Codeausschnitts; der Endzustand ist dargestellt:

```aquascope,interpreter
#fn main() {
let a = Box::new(15);
let b = a;
let c = Box::new(15);`[]`
#}
```

Wie viele Kopien der Zahl `15` gibt es im Endzustand irgendwo im Speicher? Gib deine Antwort als Ziffer an, z. B. 0 oder 1.
"""
answer.answer = "2"
context = """
Die beiden Boxen enthalten die zwei Kopien der Zahl 15. Die Zuweisung `let b = a` kopiert den Heap-Zeiger, aber nicht die Zahl auf dem Heap.
"""