[[questions]]
id = "0b8dbb4f-7c56-4b6e-8358-95c7b46f90c3"
type = "ShortAnswer"
prompt.prompt = """
Betrachte das folgende Programm, das den Zustand des Speichers nach der letzten Zeile zeigt:
```aquascope,interpreter
#fn main() {
let x = Box::new(0);
let y = Box::new(&x);`[]`
#}
```

Wie viele Dereferenzierungen bräuchtest du, wenn du die Zahl `0` über `y` herauskopieren wolltest?
Gib deine Antwort als Ziffer an. Wäre der richtige Ausdruck zum Beispiel `*y`, dann wäre die Antwort 1.
"""
answer.answer = "3"
context = """
`***y` ist der richtige Ausdruck. `y` hat den Typ `Box<&Box<i32>>`. Es ist ein Heap-Zeiger auf eine Stack-Referenz
auf einen Heap-Zeiger. Deshalb muss `y` dreimal dereferenziert werden, einmal für jede Indirektionsebene.
"""

[[questions]]
id = "7cf19153-3647-4afc-953a-f9392ddb96fb"
type = "MultipleChoice"
prompt.prompt = """
Betrachte das folgende Programm, das den Zustand des Speichers nach der letzten Zeile zeigt:

```aquascope,interpreter
fn get_first(vr: &Vec<i32>) -> i32 {
  vr[0]
}

fn main() {
  let mut v = vec![0, 1, 2];
  let n = get_first(&v);
  println!("{} {}", n, v[1]);`[]` 
}
```

Welche der folgenden Aussagen erklärt am besten, warum `v` nach dem Aufruf von `get_first` nicht freigegeben wird?
"""
answer.answer = "`vr` ist eine Referenz, die den Vektor, auf den sie zeigt, nicht besitzt"
prompt.distractors = [
  "`vr` wird innerhalb von `get_first` nicht verändert",
  "`get_first` gibt einen Wert vom Typ `i32` zurück, nicht den Vektor selbst",
  "`v` wird nach dem Aufruf von `get_first` im `println` verwendet"
]
context = """
Referenzen sind nicht-besitzende Zeiger. Wird `&v` an `get_first` übergeben, wird die Ownership von `v` deshalb nicht in `get_first` verschoben,
und folglich wird `v` nicht freigegeben, wenn `get_first` endet.
"""