[[questions]]
id = "cbe8ef63-4f7e-45fd-b11f-e6eba40587b0"
type = "MultipleChoice"
prompt.prompt = """
Welche der folgenden Aussagen erklärt am besten, warum ein `i32` ohne Move kopiert werden kann, ein `String` aber nicht?
"""
answer.answer = "Ein `String` besitzt Daten auf dem Heap, ein `i32` dagegen nicht"
prompt.distractors = [
    "Ein `i32` belegt weniger Speicher als ein `String`",
    "Ein `i32` ist in Rust ein primitiver Typ, ein `String` dagegen nicht",
    "Ein `String` kann auf dem Heap liegen, ein `i32` dagegen nur auf dem Stack"
]
context = """
Könnte ein `String` ohne Move kopiert werden, könnten zwei Variablen glauben, denselben
String zu besitzen, was zu einem Double-Free führen würde.
"""

[[questions]]
id = "512e1ec0-cd7b-4a90-949b-d7b08b4009a8"
type = "MultipleChoice"
prompt.prompt = """
Der folgende Codeausschnitt lässt sich nicht kompilieren:

```rust
let s = String::from("Hello world");
let s_ref = &s;
let s2 = *s_ref;
println!("{s2}");
```

Welche der folgenden Aussagen beschreibt am besten das undefinierte Verhalten, das auftreten könnte, wenn dieses Programm ausgeführt werden dürfte?
"""
answer.answer = "Der String wird am Ende des Programms zweimal freigegeben"
prompt.distractors = [
  "Das Lesen von `s2` in `println` verwendet freigegebenen Speicher",
  "Die Dereferenzierung `*s_ref` verwendet freigegebenen Speicher",
  "In diesem Programm gibt es kein undefiniertes Verhalten"
]
context = """
Das `println` ist technisch gesehen sicher, weil der String erst am Ende des aktuellen
Gültigkeitsbereichs freigegeben wird. Dann aber tritt undefiniertes Verhalten auf, weil der String zweimal
freigegeben wird, einmal für `s` und einmal für `s2`.
"""

[[questions]]
id = "1e31e163-5bd4-4385-b222-33c19058bf6a"
type = "MultipleChoice"
prompt.prompt = """
Das folgende Programm lässt sich nicht kompilieren:

```rust
fn copy_to_prev(v: &mut Vec<i32>, i: usize) {
  let n = &mut v[i];
  *n = v[i - 1];
}
fn main() {
  let mut v = vec![1, 2, 3];
  copy_to_prev(&mut v, 1);
}
```

Welche der folgenden Aussagen beschreibt am besten das undefinierte Verhalten, das auftreten könnte, wenn dieses Programm ausgeführt werden dürfte?
"""
answer.answer = "In diesem Programm gibt es kein undefiniertes Verhalten"
prompt.distractors = [
  "Die Zuweisung an `*n` verwendet freigegebenen Speicher",
  "Der Borrow `&mut v[i]` erzeugt einen Zeiger auf freigegebenen Speicher",
  "Das Lesen von `v[i - 1]` verwendet freigegebenen Speicher"
]
context = """
Dieses Programm ist sicher. Bei seiner Ausführung könnte kein undefiniertes Verhalten auftreten. (Läge `i` außerhalb
der Grenzen von `v`, würde Rust zur Laufzeit einen Panic auslösen, statt undefiniertes Verhalten zu verursachen.)

Das Problem ist, dass Rust nicht sicher weiß, dass sich `v[i]` und `v[i - 1]` auf verschiedene Elemente beziehen.
"""


[[questions]]
id = "4df75888-2cd5-4259-8629-46a307429fd0"
type = "MultipleChoice"
prompt.prompt = """
Betrachte diese Funktion, eine vereinfachte Variante der Funktion aus dem vorherigen Quiz:

```
/// Adds "Ph.D." to a person's name
fn award_phd(name: &String) {
    let mut name = *name;
    name.push_str(", Ph.D.");
}
```

Der Rust-Compiler weist diese Funktion mit folgendem Fehler zurück:

```text
error[E0507]: cannot move out of `*name` which is behind a shared reference
 --> test.rs:3:20
  |
3 |     let mut name = *name;
  |                    ^^^^^
  |                    |
  |                    move occurs because `*name` has type `String`, which does not implement the `Copy` trait
  |                    help: consider borrowing here: `&*name`
```

Nimm an, der Compiler würde diese Funktion NICHT zurückweisen. Wähle alle (falls vorhanden) der folgenden Programme aus, die bei der Ausführung
undefiniertes Verhalten verursachen könnten. Wenn keines dieser Programme undefiniertes Verhalten verursachen könnte, 
wähle „Keines dieser Programme“.
"""
answer.answer = [
"""
```
let name = String::from("Ferris");
award_phd(&name);
```
""",
"""
```
let name = String::from("Ferris");
award_phd(&name);
println!("{}", name);
```
""",
"""
```
let name = String::from("Ferris");
let name_ref = &name;
award_phd(&name);
println!("{}", name_ref);
```
""",

]
prompt.distractors = [
  "Keines dieser Programme"
]
context = """
Durch die Anweisung `let mut name = *name` übernimmt `name` die Ownership des Eingabe-Strings.
Die aufrufende Stelle behält aber ebenfalls die Ownership des Strings. Nachdem `award_phd`
endet, wird der String deshalb freigegeben. Daher hat jedes der obigen Programme undefiniertes Verhalten, 
weil `name` irgendwann ein zweites Mal freigegeben wird. Es spielt keine Rolle, ob `name`
oder eine Referenz auf `name` nach dem Aufruf von `award_phd` gelesen wird.
"""

[[questions]]
id = "1f48fda5-afc6-440b-a9aa-53dc8d54efaa"
type = "Tracing"
prompt.program = """
fn main() {
    let mut point = [0, 1];
    let mut x = point[0];
    let y = &mut point[1];
    x += 1;
    *y += 1;
    println!("{} {}", point[0], point[1]);
}
"""
answer.doesCompile = true
answer.stdout = "0 2"
context = """
Dieses Programm lässt sich kompilieren, weil die Bindung von `x` `point[0]` kopiert, sodass `y` `point[1]` veränderlich ausleihen kann.
Die Veränderung `x += 1` wirkt sich nicht auf `point` aus, die Veränderung `*y += 1` dagegen schon; das Endergebnis ist also `0 2`.
"""