[[questions]]
id = "97781ca8-ad58-449c-9769-e20b9d2e42a6"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du hast eine Variable `v` vom Typ `&mut Vec<i32>` und willst die Methode `len` mit der
folgenden Signatur aufrufen:

```
impl Vec<i32> {
  fn len(&self) -> usize {
    /* ... */
  }
}
```

Welche der folgenden Aussagen beschreibt am besten, was passiert, wenn du versuchst, den Ausdruck `v.len()` zu kompilieren?
"""
answer.answer = "Er lässt sich kompilieren, weil die `&mut`-Referenz implizit als `&`-Referenz erneut ausgeliehen wird"
prompt.distractors = [
  "Er lässt sich nicht kompilieren, weil `&mut Vec<i32>` nicht derselbe Typ ist wie `&Vec<i32>`",
  "Er lässt sich nicht kompilieren, weil `v` nicht explizit dereferenziert wird",
  "Er lässt sich kompilieren, weil `&self` jede Art von Referenz annehmen kann"
]
context = """
Der Ausdruck `v.len()` wird zu `Vec::len(&*v)` aufgelöst, einem gültigen erneuten Borrow von `v`, daher lässt sich dieser Ausdruck kompilieren.
Du kannst `v` aber nicht direkt an `Vec::len` übergeben, weil sich `&self` ausdrücklich auf unveränderliche Referenzen bezieht.
"""

[[questions]]
id = "35a75881-eb08-486c-92b3-413ab512138a"
type = "MultipleChoice"
prompt.prompt = """
Betrachte diese beiden Methoden, die ein Feld eines Structs erhöhen. Welcher Stil wäre in Rust idiomatischer?

```
struct Point(i32, i32);
impl Point {
  fn incr_v1(mut self)  { self.0 += 1; }
  fn incr_v2(&mut self) { self.0 += 1; }
}
```
"""
answer.answer = "`incr_v2`"
prompt.distractors = [
  "`incr_v1`",
  "Beide sind idiomatisch",
  "Keine von beiden ist idiomatisch"
]
prompt.answerIndex = 1
context = """
Die Methode `incr_v1` ist nicht idiomatisch, weil sie die Ownership des `Point` übernimmt. Nach dem Aufruf von `p.incr_v1()` wäre `p` also 
unbrauchbar, was für diese Methode vermutlich nicht beabsichtigt ist.
"""

[[questions]]
id = "03a0a1ec-8ce6-40f2-b8b7-6dd5402aeb7d"
type = "Tracing"
prompt.program = """
struct Point(i32, i32);
impl Point {
  fn incr_x(&mut self) {
    self.0 += 1;
  }
}

fn main() {
  let mut p = Point(0, 0);
  p.incr_x();
  println!("{}", p.0);
}
"""
answer.doesCompile = true
answer.stdout = "1"
context = """ 
Denk daran, dass `.0` bei Tupel-Structs wie `Point` gültig ist.
"""

[[questions]]
id = "be7be598-8a31-4c1a-9171-4ff90f512430"
type = "Tracing"
prompt.program = """
struct Point {
  x: i32,
  y: i32
}

impl Point {
  fn get_x(&mut self) -> &mut i32 {
    &mut self.x
  }
}

fn main() {
  let mut p = Point { x: 1, y: 2 };
  let x = p.get_x();
  *x += 1;
  println!("{} {}", *x, p.y);
}
"""
answer.doesCompile = false
answer.lineNumber = 16
context = """ 
Weil `get_x` ganz `p` veränderlich ausleiht, kann ein Programm `p` auf keine Weise verwenden, bis `x` nicht mehr verwendet wird. 
Deshalb ist es ein Ownership-Fehler, `x` und `p.y` in derselben Zeile zu lesen.
"""