[[questions]]
id = "ae4e06f6-5fdc-43d9-929c-85eba3559a82"
type = "MultipleChoice"
prompt.prompt = "Welches Schlüsselwort steht in Rust für Konstruktorfunktionen?"
answer.answer = "Keines der genannten"
prompt.distractors = [
  "`constructor`",
  "`new`",
  "Der Name des Typs, der konstruiert wird",
]
prompt.answerIndex = 3
context = """
Rust hat kein Schlüsselwort für Konstruktorfunktionen. Idiomatisch definiert man eine Konstruktorfunktion als assoziierte Funktion namens `new`, 
aber die Sprache erzwingt das nicht.
"""

[[questions]]
id = "a506f97d-2b51-4517-bc4d-f69764093c71"
type = "Tracing"
prompt.program = """
struct Point(i32, i32);
fn main() {
  let p = Point(1, 2);

  impl p {
    fn x(&self) -> i32 { self.0 }
  }
  
  println!("{}", p.x());
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """ 
Methoden können nur für Typen (z. B. `impl Point`) implementiert werden, nicht für Variablen (wie `p`).
"""