[[questions]]
id = "f0ec64fa-262f-4819-8379-acad7aaf8be2"
type = "Tracing"
prompt.program = """
#[derive(Debug)]
struct Rectangle {
  width: u32,
  height: u32,
}

fn main() {
  let rect1 = Rectangle {
    width: 30,
    height: 50,
  };

  let a = area(rect1);
  println!("{} * {} = {}", rect1.width, rect1.height, a);
}

fn area(rectangle: Rectangle) -> u32 {
  rectangle.width * rectangle.height
}
"""
answer.doesCompile = false
answer.lineNumber = 14
context = """ 
Die Funktion `area` übernimmt die Ownership ihres Arguments `rectangle`. Der Aufruf `area(rect1)` verschiebt
`rect1` deshalb, sodass es in der nächsten Zeile nicht mehr verwendet werden kann.
"""

[[questions]]
id = "9ce4156e-4112-4101-a2c7-51758ceca639"
type = "MultipleChoice"
prompt.prompt = "Welche Aussage beschreibt am besten einen Unterschied zwischen den Traits `Display` und `Debug`?"
answer.answer = "`Display` dient dazu, Werte Endnutzern zu präsentieren, `Debug` dagegen dem internen Gebrauch durch Entwickler"
prompt.distractors = [
  "`Display` dient dazu, Werte auf der Konsole auszugeben, `Debug` dagegen dazu, Werte in einem Debugger anzusehen",
  "`Display` kann nicht für Structs implementiert werden, `Debug` dagegen schon",
  "Es gibt keinen Unterschied, `Display` und `Debug` sind Aliasse für denselben Trait."
]
