[[questions]]
id = "5b6e4016-c089-4cb3-96a7-ca9f88694488"
type = "Tracing"
prompt.program = """
enum Location {
  Point(i32),
  Range(i32, i32)
}

fn main() {
  let l: Location = Location::Range(0, 5);
  let n = match l {
    Location::Point(_) => -1,
    Location::Range(_, 5) => 5,
    Location::Range(0, _) => 0,
    _ => -2
  };
  println!("{n}");
}
"""
answer.doesCompile = true
answer.stdout = "5"
context = """ 
Die Arme werden von oben nach unten ausprobiert. Sowohl das zweite als auch das dritte Pattern passen, also wird das zweite verwendet.
"""


[[questions]]
id = "f7c361e0-733a-4d48-9809-736e3c1e2b67"
type = "MultipleChoice"
prompt.prompt = """
Betrachte diese Methode, die für den Typ `Option` implementiert ist:

```
impl<T> Option<T> {
  fn unwrap_or(self, other: T) -> T {
    match self {
      Some(t) => t,
      None => other
    }
  }
}
```

Welcher Satz beschreibt das Verhalten dieser Funktion am besten?
"""
answer.answer = "Gibt das Objekt in `self` zurück, falls vorhanden, und andernfalls `other`"
prompt.distractors = [
  "Gibt eine neue Option zurück, die das Objekt in `self` enthält, falls vorhanden, und andernfalls `other`",
  "Fügt `other` in `self` ein, falls `self` noch keinen Wert enthält",
  "Gibt eine Referenz auf das Objekt in `self` zurück, falls vorhanden, und andernfalls `other`"
]
context = """
Diese Funktion „packt“ die Option „aus“ (*unwrap*), indem sie ihre Ownership übernimmt und den Wert darin herausholt; ist kein Wert vorhanden, gibt sie ersatzweise `other` zurück.
Diese Funktion gibt es tatsächlich in der Standardbibliothek!
"""


[[questions]]
id = "1e4f082c-ffa4-4d33-8726-2dbcd72e1aa2"
type = "Tracing"
prompt.program = """
#[derive(Debug)]
enum Either {
  Left(usize),
  Right(String)
}

fn main() {
  let x = Either::Right(String::from("Hello world"));
  let value = match x {
    Either::Left(n) => n,
    Either::Right(s) => s.len()
  };
  println!("{x:?} {value}");
}
"""
answer.doesCompile = false
answer.lineNumber = 13
context = """
Der Arm `Either::Right(s)` verschiebt das Feld `s`, daher kann `x` im `println` nicht verwendet werden.
"""


[[questions]]
id = "6e012d34-5c59-443e-85d9-385f0d7dee13"
type = "MultipleChoice"
prompt.prompt = """
Betrachte diese beiden Implementierungen einer Funktion, die eine vorzeichenlose Zahl zweimal dekrementiert.

```
fn decr_twice_v1(n: u32) -> Option<u32> {
  match n {
    0 => None,
    1 => None,
    n2 => Some(n2 - 2)
  }
}

fn decr_twice_v2(n: u32) -> Option<u32> {
  if n == 0 {
    None
  } else if n == 1 {
    None
  } else {
    Some(n - 2)
  }
}
```

Die Funktionen verhalten sich gleich für:
"""
answer.answer = "Alle Eingaben"
prompt.distractors = [ "Keine Eingaben", "Einige, aber nicht alle Eingaben" ]
context = """
`match` und `if` erfüllen hier dieselbe Funktion. Ein Match-Ausdruck ist wie ein spezialisiertes `if`, das auf Gleichheit mit dem verglichenen Objekt prüft.
"""