[[questions]]
id = "770f09d3-110d-4505-b41a-2af422198d59"
type = "Tracing"
prompt.program = """
fn foo(x: &i32) { 
  println!("{x}");
}

fn main() {
  let x = null;
  foo(x);
}
"""
answer.doesCompile = false
answer.lineNumber = 6
context = """ 
Rust hat keine Null-Zeiger, daher gibt es das Schlüsselwort `null` nicht. Um auszudrücken, dass ein Objekt möglicherweise null ist, sollte ein Option-Typ verwendet werden.
"""

[[questions]]
id = "6226be11-31c3-4cac-b97c-515514a70af2"
type = "MultipleChoice"
prompt.prompt = """
Betrachte diese beiden Darstellungen eines `Result`-Typs, der einen Wert `T` enthält, wenn eine Berechnung erfolgreich ist, oder einen Fehler `E`, wenn sie fehlschlägt.

```
struct Result1<T, E> {
  ok: Option<T>,
  err: Option<E>,
}

enum Result2<T, E> {
  Ok(T),
  Err(E)
}
```

Das Enum `Result2` gilt in Rust als idiomatischer als das Struct `Result1`. 
Welche der folgenden Aussagen ist **KEIN** gültiger Grund dafür?
"""
answer.answer = "Das Struct enthält `Option`-Typen, die nur dafür gedacht sind, Structs zu umhüllen"
prompt.distractors = [
  "Das Struct belegt zur Laufzeit mehr Speicher als das Enum",
  "Beim Struct könnten `ok` und `err` beide `None` sein, das Enum muss dagegen mindestens eines davon haben",
  "Das Struct ist syntaktisch umständlicher zu konstruieren als das Enum"
]
context = """
Es ist völlig in Ordnung, wenn Structs `Option`-Typen als Felder enthalten (gefragt war nach dem, was **KEIN** gültiger Grund ist).
Wenn deine Datenstruktur aber Invarianten hat wie „genau eines von zwei optionalen Feldern soll `Some` sein“,
dann lässt sich diese Invariante mit einem Enum besser sicherstellen.
"""


