[[questions]]
id = "b2e05b2a-1f98-4498-9a9b-e1e358adf476"
type = "MultipleChoice"
prompt.prompt = """
Welches Kontrollflusskonstrukt wäre in der folgenden Funktion am idiomatischsten?

```
enum Location {
  Point(i32),
  Range(i32, i32)
}

fn print_range_max(loc: &Location) {  
  // print the second field of Range, if loc is a Range
}
```
"""
answer.answer = "`if let`"
prompt.distractors = [
  "`match`"  
]
context = """
Wenn die Funktion nur in einem Fall etwas bewirkt, ist ein `if let` am idiomatischsten.
"""

[[questions]]
id = "fe17286b-67ed-43a7-a1df-10afee7921cc"
type = "MultipleChoice"
prompt.prompt = """
Welches Kontrollflusskonstrukt wäre in der folgenden Funktion am idiomatischsten?

```
enum Location {
  Point(i32),
  Range(i32, i32)
}

fn get_start(loc: &Location) -> i32 { 
  // return the first field of Range or the only field of Point  
}
```
"""
answer.answer = "`match`"
prompt.distractors = [
  "`if let`",
]
context = """ 
Wenn die Funktion für jeden Fall einen Wert zurückgeben muss, ist ein `match` am besten geeignet.
"""
