[[questions]]
id = "6e5e193e-579d-4a46-aae4-d35336b77b68"
type = "MultipleChoice"
prompt.prompt = """
**Programm 1:**

```ide
/// Makes a string to separate lines of text, 
/// returning a default if the provided string is blank
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        user_str
    }
}
```

Welche der folgenden Fehlermeldungen beschreibt am besten den Compilerfehler, den du beim Kompilieren dieser Funktion bekommen würdest?
"""
answer.answer = "cannot return reference to local variable `default`"
prompt.distractors = [
  "`user_str` does not live long enough",
  "function `make_separator` cannot return a reference of type `&str`",
  "function `make_separator` cannot return two different references"
]
context = """
Weil `default` innerhalb von `make_separator` auf dem Stack lebt, wird es freigegeben, sobald ein Aufruf von `make_separator` endet.
Dann zeigt `&default` auf freigegebenen Speicher. Rust beschwert sich deshalb, dass man keine Referenz auf eine lokale Variable zurückgeben kann.
"""

[[questions]]
id = "44a2eb01-b49a-497b-a9d2-207814d1db1e"
type = "MultipleChoice"
prompt.prompt = """
**Programm 1:**

```ide
/// Makes a string to separate lines of text, 
/// returning a default if the provided string is blank
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        user_str
    }
}
```

Wenn du versuchst, diese Funktion zu kompilieren, gibt der Compiler normalerweise folgenden Fehler aus:

```text
error[E0515]: cannot return reference to local variable `default`
 --> test.rs:6:9
  |
6 |         &default
  |         ^^^^^^^^ returns a reference to data owned by the current function
```

Nimm an, der Compiler würde diese Funktion NICHT zurückweisen. Welche (falls überhaupt) der folgenden Programme würden
(1) den Compiler passieren und (2) bei der Ausführung möglicherweise undefiniertes Verhalten verursachen?
Wähle jedes Programm aus, das beide Kriterien erfüllt, ODER wähle „Keines dieser Programme“, wenn keines sie erfüllt.
"""
answer.answer = ["""
```
let s = make_separator("");
println!("{s}");
```
"""]
prompt.distractors = [
"""
```
println!("{}", make_separator("Hello world!"));
```
""",
"Keines dieser Programme",
]
context = """
Die aufrufende Stelle muss einen leeren String übergeben, um die problematische if-Bedingung auszulösen. Diese gibt einen hängenden Zeiger zurück.
"""

[[questions]]
id = "815ae4cd-0f23-4da5-9dc2-0e81c664cc28"
type = "MultipleChoice"
prompt.prompt = """
**Programm 1:**

```ide
/// Makes a string to separate lines of text, 
/// returning a default if the provided string is blank
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        user_str
    }
}
```

Welche der folgenden Korrekturen (gelb hervorgehoben) erfüllt diese drei Kriterien am besten:
1. Die korrigierte Funktion besteht den Rust-Compiler,
2. die korrigierte Funktion bewahrt die Absicht des ursprünglichen Codes und
3. die korrigierte Funktion führt keine unnötigen Ineffizienzen ein?
"""
answer.answer = """
```ide
fn make_separator(user_str: &str) -> `[String]` {
    if user_str == "" {
        let default = "=".repeat(10);
        `[default]`
    } else {
        `[user_str.to_string()]`        
    }
}
```
"""
prompt.distractors = [
"""
```ide
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        `[&user_str]`
    }
}
```
""",
"""
```ide
fn make_separator(user_str: `[String]`) -> `[String]` {
    if user_str == "" {
        let default = "=".repeat(10);
        `[default]`
    } else {
        user_str
    }
}
```
""",
]
context = """
Es gibt keine gültige Möglichkeit, einen Zeiger auf eine auf dem Stack allozierte Variable zurückzugeben. Die einfache Lösung ist daher, den Rückgabetyp in `String` zu ändern
und die Eingabe `user_str` in einen String zu kopieren, der seine Daten besitzt. Würde man aber verlangen, dass `user_str` ein `String` ist, würde die API unflexibler, z. B.
könnte eine aufrufende Stelle `make_separator` nicht mit einem Teilstring eines größeren Strings aufrufen. Außerdem müssten aufrufende Stellen Strings auf dem Heap allozieren, z. B.
könnten sie kein String-Literal wie in `make_separator("Rust")` verwenden.

Die idiomatischste Lösung für dieses Problem verwendet ein Konstrukt, das du noch nicht kennst: [`Cow`](https://doc.rust-lang.org/std/borrow/enum.Cow.html).
Dieser Smart-Pointer mit Clone-on-Write würde es der Funktion ermöglichen, ohne Typfehler *entweder* einen String mit eigenen Daten *oder* eine String-Referenz zurückzugeben.
"""

[[questions]]
id = "1f4e5c06-ecdf-481d-9cae-8a25dafe9cfd"
type = "MultipleChoice"
prompt.prompt = """
**Programm 2:**

```ide
/// Gets the string out of an option if it exists,
/// returning a default otherwise
fn get_or_default(arg: &Option<String>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```

Welche der folgenden Fehlermeldungen beschreibt am besten den Compilerfehler, den du beim Kompilieren dieser Funktion bekommen würdest?
"""
answer.answer = "cannot move out of `arg` in `arg.unwrap()`"
prompt.distractors = [
  "cannot call `arg.is_none()` without dereferencing `arg`",
  "`arg` does not live long enough",
  "cannot return `s.clone()` which does not live long enough"
]
context = """
Die Funktion `Option::unwrap` erwartet `self`, also die Ownership von `arg`. `arg` ist aber eine unveränderliche
Referenz auf eine Option und kann daher keine Ownership der Option liefern. Deshalb beschwert sich der Compiler, dass wir 
nicht über `unwrap` aus `arg` herausverschieben können.
"""


[[questions]]
id = "989670b2-b038-47c4-9975-a93d6ee193e5"
type = "MultipleChoice"
prompt.prompt = """
**Programm 2:**

```ide
/// Gets the string out of an option if it exists,
/// returning a default otherwise
fn get_or_default(arg: &Option<String>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```

Wenn du versuchst, diese Funktion zu kompilieren, gibt der Compiler normalerweise folgenden Fehler aus:

```text
error[E0507]: cannot move out of `*arg` which is behind a shared reference
   --> test.rs:7:13
    |
7   |     let s = arg.unwrap();
    |             ^^^^--------
    |             |   |
    |             |   `*arg` moved due to this method call
    |             help: consider calling `.as_ref()` or `.as_mut()` to borrow the type's contents
    |             move occurs because `*arg` has type `Option<String>`, which does not implement the `Copy` trait
```

Nimm an, der Compiler würde diese Funktion NICHT zurückweisen. Welche (falls überhaupt) der folgenden Programme würden
(1) den Compiler passieren und (2) bei der Ausführung möglicherweise undefiniertes Verhalten verursachen?
Wähle jedes Programm aus, das beide Kriterien erfüllt, ODER wähle „Keines dieser Programme“, wenn keines sie erfüllt.
"""
answer.answer = [
"""
```
let opt = Some(String::from("Rust"));
get_or_default(&opt);
println!("{:?}", opt);
```
""",
"""
```
let opt = Some(String::from("Rust"));
let s = get_or_default(&opt);
println!("{}", s);
```
""", 
"""
```
let opt = Some(String::from("Rust"));
get_or_default(&opt);
```
""", 
]
prompt.distractors = [
"Keines dieser Programme",
]
context = """
Alle diese Programme verletzen die Speichersicherheit durch einen Double-Free. Wäre `arg.unwrap()` erlaubt, würde
`s` die Ownership des Strings `String::from("Rust")` übernehmen. Nachdem `get_or_default` zurückgekehrt ist,
würde der String freigegeben. `opt` glaubt aber ebenfalls, den String zu besitzen, also 
würde der String ein zweites Mal für `opt` freigegeben.
"""

[[questions]]
id = "3a8d5bb8-a204-43e6-b50a-d17c803dbe37"
type = "MultipleChoice"
prompt.prompt = """
**Programm 2:**

```ide
/// Gets the string out of an option if it exists,
/// returning a default otherwise
fn get_or_default(arg: &Option<String>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```

Welche der folgenden Korrekturen (gelb hervorgehoben) erfüllt diese drei Kriterien am besten:
1. Die korrigierte Funktion besteht den Rust-Compiler,
2. die korrigierte Funktion bewahrt die Absicht des ursprünglichen Codes und
3. die korrigierte Funktion führt keine unnötigen Ineffizienzen ein?
"""
answer.answer = """
```ide
fn get_or_default(arg: &Option<String>) -> String {
    `[match arg {]`
        `[None => String::new(),]`
        `[Some(s) => s.clone()]`
    `[}]`
}
```
"""
prompt.distractors = [
"""
```ide
fn get_or_default(arg: `[&mut Option<String>]`) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg`[.as_mut()]`.unwrap();
    s.clone()
}
```
""",
"""
```ide
fn get_or_default(arg: `[Option<String>]`) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```
""",
"""
```ide
fn get_or_default(arg: &Option<`[&str]`>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    `[s.to_string()]`
}
```
""",
]
context = """
Die Kombination aus `is_none` und `unwrap` ist hier ein Anti-Pattern in Rust, weil ein `match` beide Funktionalitäten vereint und
automatisch die Referenz `&Option` nach innen schiebt, sodass ein `&String` entsteht. Deshalb ist die `match`-Lösung
die idiomatischste und besteht den Compiler, ohne die beabsichtigte Typsignatur der Funktion zu ändern.

Die Lösung, `&Option` in `Option` zu ändern, ist nicht wünschenswert, weil die aufrufende Stelle dann die Ownership ihrer Option abgeben muss,
was eine weitaus restriktivere API ist.
"""