[[questions]]
id = "4e18f340-e336-43c5-9a95-79dec1f49945"
type = "ShortAnswer"
prompt.prompt = "Welches Schlüsselwort verwendest du am Anfang eines absoluten Pfades zu einem Element im aktuellen Crate?"
answer.answer = "crate"
context = """
Ein absoluter Pfad zum Element `b` im Modul `a` wäre zum Beispiel `crate::a::b`.
"""

[[questions]]
id = "256d0ce2-da89-4b44-94da-177634fc633a"
type = "Tracing"
prompt.program = """
pub mod foo {
  fn a() { println!("a"); }
  mod bar {
    pub fn b() { println!("b"); }
  }
}

fn main() {
  foo::bar::b();
}
"""
answer.doesCompile = false
answer.lineNumber = 9
context = """
`b` ist für `main` nicht zugänglich, weil das Modul `bar` nicht mit `pub` gekennzeichnet ist.
"""

[[questions]]
id = "5e78e2e4-81dc-42b2-8527-f08b5117982f"
type = "Tracing"
prompt.program = """
pub mod foo {
  pub mod bar {
    pub fn b() { println!("b");  }
  }
  pub fn a() { bar::b(); }
}

fn main() {
  foo::a();
}
"""
answer.doesCompile = true
answer.stdout = "b"
context = """
Innerhalb von `foo` ist es zulässig, mit einem relativen Pfad auf Elemente in `bar` zu verweisen.
"""
