[[questions]]
id = "a162c2c8-aadf-4963-a997-02a1035f2459"
type = "MultipleChoice"
prompt.prompt = "Welche der folgenden Aussagen beschreibt die Funktion des Schlüsselworts `use` am besten?"
answer.answer = "`use` macht Verweise auf Elemente im eingebundenen Pfad weniger umständlich"
prompt.distractors = [
  "`use` kopiert den Inhalt eines Elements von einem Modul in ein anderes",
  "`use` ermöglicht einen Zugriff auf Elemente, der die normalen Sichtbarkeitsregeln umgeht",
  "`use` teilt dem Compiler mit, dass ein Element verwendet wird und optimiert werden soll"
]
context = """
Mit `use` werden Verweise auf Elemente im eingebundenen Pfad kürzer als ohne das `use`, was Verweise weniger umständlich macht.
"""


[[questions]]
id = "eccc2099-9880-4628-8474-f1d55e2a4a4a"
type = "ShortAnswer"
prompt.prompt = """
Betrachte dieses Modul und diese `use`-Anweisung:

```
pub mod parent {
  pub fn a() {}
  fn b() {}
  pub mod child {
    pub fn c() {}
  }
}

fn main() {
  use parent::{*, child as alias};
  // ...
}
```

Wie viele Pfade gibt es innerhalb von `main` insgesamt, die auf `a`, `b` oder `c` verweisen können (ohne solche, die `self`, `super` oder `crate` verwenden)?
Gib deine Antwort als Ziffer an, etwa 0 oder 1. Wären zum Beispiel `a` und `parent::b` die einzigen beiden gültigen Pfade, wäre die Antwort 2.
"""
answer.answer = "5"
context = """
Es gibt zwei Pfade zu `a`: `parent::a` und `a`. Zu `b` gibt es keine Pfade, weil es privat ist. Zu `c` gibt es drei Pfade:
`parent::child::c`, `child::c`, `alias::c`.
"""