[[questions]]
id = "23c95879-aae2-4121-bf89-21278f7b6ec6"
type = "MultipleChoice"
prompt.prompt = """
Was ist KEIN Vorteil von Modulen?
"""
answer.answer = "Module steigern die Laufzeitperformance von voneinander abhängigem Code innerhalb desselben Moduls"
prompt.distractors = [
  "Module gruppieren zusammengehörigen Code, sodass Programmierende leichter an einer großen Codebasis arbeiten können",
  "Module kapseln Implementierungsdetails, die von externen Nutzern nicht verwendet werden sollten",
  "Module bieten einen Gültigkeitsbereich, um Namenskonflikte zwischen Teilen einer Codebasis zu vermeiden"
]
context = """
Module haben keine Auswirkung auf die Laufzeit, sie dienen rein der Organisation zur Kompilierzeit.
"""
