[[questions]]
id = "8ef2f170-71d9-4f17-a688-b99d8c8072a8"
type = "Tracing"
prompt.program = """
pub mod a {
  pub mod b {
    pub fn f() { println!("b1"); }
    pub mod c {
      pub fn f() { println!("c1"); }
    }
  }
  pub fn entry() { super::b::c::f(); }
}

pub mod b {
  pub fn f() { println!("b2"); }
  pub mod c {
    pub fn f() { println!("c2"); }
  }
}

fn main() {
  crate::a::entry();
}
"""
answer.doesCompile = true
answer.stdout = "c2"
context = """
`entry` verwendet den Pfad `super::b::c::f`. `entry` liegt im Modul `a`, also verweist `super` auf das Elternmodul von `a`, also die Wurzel des Crates. 
Das Kind `b` der Wurzel ist dann das äußerste Modul `b`, dessen Kind `c` eine Funktion `f` enthält, die `"c2"` ausgibt.
"""

[[questions]]
id = "153b12b3-4fbc-449c-99a6-7a2cd469df0f"
type = "Tracing"
prompt.program = """
pub mod point {
  #[derive(Debug)]
  pub struct Point(i32, i32);

  impl Point {
    pub fn origin() -> Self { Point(0, 0) }
  }
}

fn main() {
  let mut p = point::Point::origin();
  p.0 += 1;
  println!("{p:?}");
}
"""
answer.doesCompile = false
answer.lineNumber = 12
context = """
Das Struct `Point` und die statische Methode `origin` sind zwar beide öffentlich, aber das Feld `i32` ist nicht mit pub gekennzeichnet. Daher ist ein direkter Zugriff auf `p.0` außerhalb
des Moduls `point` nicht erlaubt. Dieses Programm würde kompilieren, wenn Zeile 3 zu `pub struct Point(pub i32, pub i32)` geändert würde.
"""