[[questions]]
id = "6a94bc90-6cc5-4a47-838c-596d3747b7e4"
type = "ShortAnswer"
prompt.prompt = """
Stell dir ein Rust-Paket mit folgender Verzeichnisstruktur vor:

```text
foobar
├── Cargo.toml
└── src/
    ├── lib.rs
    ├── engine.rs
    └── engine/
        └── analysis.rs
```

Die Dateien haben folgenden Inhalt:


```
// engine/analysis.rs
pub fn run() {}
```

```
// engine.rs
mod analysis;
pub use analysis::*;
```

```
// lib.rs
pub mod engine;
```

Angenommen, jemand anderes verwendet das Library-Crate `foobar` in einem separaten Paket und möchte die Funktion `run` aufrufen. 
Welchen Pfad würde diese Person schreiben?
"""
answer.answer = "foobar::engine::run"
answer.alternatives = ["foobar::engine::run()"]
context = """
Diese Verzeichnisstruktur erzeugt folgenden Modulbaum:

```text
foobar
└── engine
    └── run  
```

Daher lautet der Pfad zu `run` `foobar::engine::run`.
"""
