[[questions]]
id = "867e5d29-c1eb-44b3-99e3-bb2325b74e44"
type = "MultipleChoice"
prompt.prompt = """
**Programm 1:**

```ide
/// Removes all the zeros in-place from a vector of integers.
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```

Welche der folgenden Fehlermeldungen beschreibt am besten den Compilerfehler, den du beim Kompilieren dieser Funktion bekommen würdest?
"""
answer.answer = "`v.remove(i)` cannot borrow `v` as mutable"
prompt.distractors = [
  "`v` does not live long enough to call `v.remove(i)`",
  "`t` cannot be dereferenced while `i` is live",
  "`v.iter()` cannot be called on a mutable reference"
]
context = """
Die Funktion `v.iter()` leiht einen Vektor `v` für die Dauer der for-Schleife unveränderlich aus (*borrows*). `v.remove(i)` braucht jedoch eine veränderliche
Referenz auf `v`. Daher kann `v.remove(i)` `v` nicht veränderlich ausleihen, weil das mit dem Iterator in Konflikt stünde.
"""


[[questions]]
id = "dd1bd092-ef8d-4293-a4d6-6a59b5887e98"
type = "MultipleChoice"
prompt.prompt = """
**Programm 1:**

```ide
/// Removes all the zeros in-place from a vector of integers.
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```

Wenn du versuchst, diese Funktion zu kompilieren, gibt der Compiler normalerweise folgenden Fehler aus:

```text
error[E0502]: cannot borrow `*v` as mutable because it is also borrowed as immutable
 --> test.rs:5:13
  |
3 |     for (i, t) in v.iter().enumerate().rev() {
  |                   --------------------------
  |                   |
  |                   immutable borrow occurs here
  |                   immutable borrow later used here
4 |         if *t == 0 {
5 |             v.remove(i);
  |             ^^^^^^^^^^^ mutable borrow occurs here
```

Nimm an, der Compiler würde diese Funktion NICHT zurückweisen. Welche (falls überhaupt) der folgenden Programme würden
(1) den Compiler passieren und (2) bei der Ausführung möglicherweise undefiniertes Verhalten verursachen?
Wähle jedes Programm aus, das beide Kriterien erfüllt, ODER wähle „Keines dieser Programme“, wenn keines sie erfüllt.
"""
answer.answer = [
"""
```
let mut v = vec![5, 5, 0];
remove_zeros(&mut v);
println!("{:?}", v);
```
""",
"""
```
let mut v = vec![1, 2, 0, 3];
remove_zeros(&mut v);
```
""", 
]
prompt.distractors = [
"""
```
let mut v = vec![1; 100];
remove_zeros(&mut v);
```
""",
"Keines dieser Programme",
]
context = """
Um die Speichersicherheit zu verletzen, muss `remove_zeros` mit einem Vektor aufgerufen werden, der nach dem ersten Element eine Null enthält.
Der Aufruf `v.shrink_to_fit()` gibt Speicher frei, der dem Vektor gehört (wegen der Größenänderung), und macht dadurch den
Iterator `v.iter()` ungültig, der einen Zeiger auf die alten Daten enthält. Beachte, dass es für die Sicherheitsverletzung nicht entscheidend ist,
den Vektor `v` nach dem Aufruf von `remove_zeros` zu lesen, denn das Problem liegt innerhalb von `remove_zeros`.
"""

[[questions]]
id = "c7e7e1e1-2788-4dd9-9c18-436bc95b405f"
type = "MultipleChoice"
prompt.prompt = """
**Programm 1:**

```ide
/// Removes all the zeros in-place from a vector of integers.
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```

Welche der folgenden Korrekturen (gelb hervorgehoben) erfüllt diese drei Kriterien am besten:
1. Die korrigierte Funktion besteht den Rust-Compiler,
2. die korrigierte Funktion bewahrt die Absicht des ursprünglichen Codes und
3. die korrigierte Funktion führt keine unnötigen Ineffizienzen ein?
"""
answer.answer = """
```ide
fn remove_zeros(v: &mut Vec<i32>) {
    for `[i in (0 .. v.len()).rev()]` {
        if `[v[i]]` == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```
"""
prompt.distractors = [
"""
```ide
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v`[.clone()]`.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```
""",
"""
```ide
fn remove_zeros(v: `[&]`Vec<i32>) `[-> Vec<i32>]` {
    `[let mut new_vec = Vec::new();]`
    for (i, t) in v.iter().enumerate().rev() {
        if *t `[!=]` 0 {
            `[new_vec.push(*t)]`
        }
    }
    `[new_vec]`
}
```
""",
"""
```ide
fn remove_zeros(v: `[Vec<i32>]`) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```
""",
]
context = """
Jede Strategie, die einen neuen Vektor alloziert, ob mit `Vec::clone` oder `Vec::new`, erfordert eine unnötige zusätzliche Allokation.
Die einfachste funktionierende Strategie ist daher, nur über die Indizes `0 .. v.len()` zu iterieren, was `v` nicht ausleiht. Wir tun das
in umgekehrter Reihenfolge, damit wir keine Indizes entfernen, die es nicht mehr gibt.

Wie bei Problem 1 ist die idiomatischste Strategie eigentlich eine eingebaute Funktion, die wir noch nicht besprochen haben:
[`Vec::retain`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.retain). Diese Funktion behält in einem Vektor nur die Elemente,
die ein Prädikat erfüllen, und geht dabei sparsamer mit Speicher um.
"""

[[questions]]
id = "fb0e3080-7cc8-4338-948e-fae693d137c8"
type = "MultipleChoice"
prompt.prompt = """
**Programm 2:**

```ide
/// Reverses the elements of a vector in-place
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut v[n - i - 1]);
    }
}
```

Welche der folgenden Fehlermeldungen beschreibt am besten den Compilerfehler, den du beim Kompilieren dieses Programms bekommen würdest?
"""
answer.answer = "cannot borrow `v` as mutable twice for `v[i]` and `v[n - i - 1]`"
prompt.distractors = [
  "cannot borrow `v` as immutable for `v.len()` when `v` is a mutable borrow",
  "cannot mutably borrow an element `v[i]` of a mutable vector"
]
context = """
Der Compiler berücksichtigt nicht die konkreten Werte der Indizes, mit denen auf ein Array zugegriffen wird. Daher wird angenommen, dass `&mut v[i]`
und `&mut v[n - i - 1]` möglicherweise auf dasselbe Element verweisen. Deshalb bekommen wir einen Fehler,
dass `v` nicht zweimal veränderlich ausgeliehen werden kann.
"""


[[questions]]
id = "4c703871-3cc3-483f-beb5-876bdbcd223b"
type = "MultipleChoice"
prompt.prompt = """
**Programm 2:**

```ide
/// Reverses the elements of a vector in-place
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut v[n - i - 1]);
    }
}
```

Wenn du versuchst, diese Funktion zu kompilieren, gibt der Compiler normalerweise folgenden Fehler aus:

```text
error[E0499]: cannot borrow `*v` as mutable more than once at a time
 --> test.rs:5:40
  |
5 |         std::mem::swap(&mut v[i], &mut v[n - i - 1]);
  |         --------------      -          ^ second mutable borrow occurs here
  |         |                   |
  |         |                   first mutable borrow occurs here
  |         first borrow later used by call
```

Nimm an, der Compiler würde diese Funktion NICHT zurückweisen. Welche (falls überhaupt) der folgenden Programme würden
(1) den Compiler passieren und (2) bei der Ausführung möglicherweise undefiniertes Verhalten verursachen?
Wähle jedes Programm aus, das beide Kriterien erfüllt, ODER wähle „Keines dieser Programme“, wenn keines sie erfüllt.
"""
answer.answer = ["Keines dieser Programme"]
prompt.distractors = [
"""
```
let mut v = vec![String::from("a"), String::from("b")];
let x = &v[0];
reverse(&mut v);
println!("{x}");
```
""",
"""
```
let mut v = vec![String::from("a"), String::from("b")];
reverse(&mut v);
```
""",
"""
```
let mut v = vec![String::from("a"), String::from("b")];
reverse(&mut v);
println!("{:?}", v);
```
""",
]
context = """
Diese Funktion kann keine Verletzung der Speichersicherheit verursachen, weil für alle `i` gilt: `i != n - i - 1`. Die beiden
veränderlichen Referenzen verweisen also immer auf verschiedene Elemente. Beachte, dass das Programm mit `let x = &v[0]` nicht
kompilieren würde, weil der Borrow-Checker von Rust nicht erlauben würde, `reverse` aufzurufen, solange `x` aktiv ist.
"""

[[questions]]
id = "380fc77f-190d-4386-9e0e-f9360bbbfd98"
type = "MultipleChoice"
prompt.prompt = """
**Programm 2:**

```ide
/// Reverses the elements of a vector in-place
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut v[n - i - 1]);
    }
}
```

Welche der folgenden Korrekturen (gelb hervorgehoben) erfüllt diese drei Kriterien am besten:
1. Die korrigierte Funktion besteht den Rust-Compiler,
2. die korrigierte Funktion bewahrt die Absicht des ursprünglichen Codes und
3. die korrigierte Funktion führt keine unnötigen Ineffizienzen ein?
"""
answer.answer = """
```ide
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        `[let p1 = &mut v[i] as *mut String;]`
        `[let p2 = &mut v[n - i - 1] as *mut String;]`
        `[unsafe { std::ptr::swap_nonoverlapping(p1, p2, 1); }]`
    }
}
```
"""
prompt.distractors = [
"""
```ide
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    `[let mut v2 = v.clone();]`
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut `[v2]`[n - i - 1]);
    }
}
```
""",
"""
```ide
fn reverse(v: `[&Vec<String>]`) -> `[Vec<String>]` {
    let n = v.len();
    `[let mut v2 = Vec::new();]`    
    for _ in 0 .. `[n]` {
        `[v2.push(v.pop().unwrap());]`
    }
    `[v2]`
}
```
""",
"""
```ide
fn reverse(v: &mut Vec<String>) {
    let n = v.len();    
    for i in 0 .. n / 2 {
        `[let s1 = v[i].clone();]`
        `[let s2 = v[n - i - 1].clone();]`
        `[v[i] = s2;]`
        `[v[n - i - 1] = s1;]`
    }
}
```
""",
]
context = """
Wenn der Borrow-Checker eine Operation zurückweist, die eigentlich sicher ist, und es keine Umgehungsmöglichkeit gibt,
ist unsicherer Code manchmal akzeptabel, wenn es entscheidend ist, Allokationen zu vermeiden. 
In diesem konkreten Fall solltest du eigentlich [`Vec::swap`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.swap) verwenden, das intern
mit gründlich getestetem `unsafe`-Code implementiert ist, ähnlich dem Code oben. 
Aber allgemein gilt: Wenn die Standardbibliothek deinen Anwendungsfall nicht unterstützt, kann `unsafe` akzeptabel sein, sofern es korrekt verwendet wird.
"""