[[questions]]
id = "1665d1ef-961f-4451-a988-ec46121531f9"
type = "MultipleChoice"
prompt.prompt = """
Welcher Aufruf dieser Funktion `find_until` löst zur Laufzeit einen Panic aus?

```
fn find_until(v: &Vec<i32>, n: i32, til: usize) -> Option<usize> {
  for i in 0 .. til {
    if v[i] == n {
      return Some(i);
    }
  }
  return None;
}
```
"""
answer.answer = "`find_until(&vec![1, 2, 3], 4, 4)`"
prompt.distractors = [
  "`find_until(&vec![1, 2, 3], 0, 0)`",
  "`find_until(&vec![1, 2, 3], 3, 3)`",
  "`find_until(&vec![1, 2, 3], 1, 4)`"
]
context = """
Ist `til = 4`, versucht die for-Schleife bei einem Vektor der Länge 3, den Vektor mit `i = 3` zu indexieren, was außerhalb der Grenzen liegt.
Bei `n = 1` löst diese Funktion keinen Panic aus, weil sie zurückkehrt, bevor sie den Index außerhalb der Grenzen erreicht.
"""

[[questions]]
id = "789dfffc-7556-443d-98ab-5d0a4db5c162"
type = "Tracing"
prompt.program = """
fn main() {
  let mut v = Vec::new();
  let s = String::from("Hello ");
  v.push(s);
  v[0].push_str("world");
  println!("original: {}", s);
  println!("new: {}", v[0]);
}
"""
answer.doesCompile = false
answer.lineNumber = 6
context = """
`Vec::push` verschiebt (*moves*) sein Argument, daher ist `s` nach dem Aufruf `v.push(s)` nicht mehr verwendbar. Der Aufruf `println!("original: {}", s)` ist daher nicht Ownership-sicher.
"""

[[questions]]
id = "66270f68-3ad6-4e79-8c73-c04d2daf9792"
type = "Tracing"
prompt.program = """
fn main() {
  let v = vec![String::from("Hello ")];
  let mut s = v[0];
  s.push_str("world");
  println!("{s}");
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
Nicht kopierbare Typen können nicht per Indexierung aus einem Vektor herausverschoben werden. Nur Methoden wie `Vec::remove` erlauben es, aus einem Vektor herauszuverschieben. Eine ausführlichere Erklärung findest du in Abschnitt 4.3 
[„Aus einer Collection kopieren oder verschieben“](ch04-03-fixing-ownership-errors.html#fixing-an-unsafe-program-copying-vs-moving-out-of-a-collection).
"""