[[questions]]
id = "da6daf92-5b2c-4f8d-97de-6905dbc77936"
type = "MultipleChoice"
prompt.prompt = "Welche Aussage erklärt am besten, warum Rust keine String-Indexierung erlaubt?"
answer.answer = "String-Indexierung ist mehrdeutig, weil Strings Folgen von Daten in mehreren Granularitäten darstellen"
prompt.distractors = [
  "String-Indexierung ist unsicher, weil sie einen Segfault oder einen Pufferüberlauf verursachen kann",
  "String-Indexierung ist ineffizient, weil Strings nullterminiert sind und sich ihre Länge daher nicht effizient berechnen lässt",
  "String-Indexierung würde Rust zu leicht benutzbar machen, und Rust-Entwickler brauchen Jobsicherheit"
]
context = """
Ein UTF-8-String lässt sich als Folge von Bytes, Zeichen oder Graphem-Clustern interpretieren. Keine davon ist zwangsläufig die „Standard“-Art,
einen String zu interpretieren, daher ergibt eine Standard-Indexierungsoperation keinen Sinn.
"""

[[questions]]
id = "9366278e-a3f5-4759-ac72-e3c7d248da44"
type = "MultipleChoice"
prompt.prompt = """
Welche Aussage beschreibt den Unterschied zwischen den Typen eines String-Slices `&str` und eines Byte-Slices `&[u8]` am besten?
"""
answer.answer = "`&str` zeigt auf Bytes, die sich immer als UTF-8 interpretieren lassen, während `&[u8]` eine beliebige Bytefolge sein kann"
prompt.distractors = [
  "`&str` zeigt immer auf Daten, die in der Binärdatei des Programms gespeichert sind, während `&[u8]` überall im Speicher liegen kann",
  "`&str` lässt sich nicht weiter in Slices zerlegen, während `&[u8]` erneut zerlegt werden kann",
  "`&str` lässt sich aus einem `String` erzeugen, während `&[u8]` nur aus einem `Vec` stammen kann"
]
context = """
`&str` ist ein Versprechen, dass die Bytefolge, auf die es zeigt, immer gültiges UTF-8 ist. Wer also z. B. einen `&str` ausgeben will,
muss nie prüfen, ob er gültig ist, oder sich Sorgen machen, versehentlich einen ungültigen String zu interpretieren.
"""