[[questions]]
id = "5af7c045-95dc-4bd0-9318-7204732e3ed5"
type = "Tracing"
prompt.program = """
fn main() {
  let mut v = vec![1, 2, 3];
  for i in &mut v {
    v.push(*i);
  }
  println!("{} {} {}", v[3], v[4], v[5]);
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
Auch wenn `v` veränderlich ausgeliehen ist, erlaubt das innerhalb der for-Schleife nur, `i` zu verändern, nicht `v`. Daher ist der Aufruf `v.push` ein Ownership-Fehler.
"""

[[questions]]
id = "e8da8773-8df2-4279-8c27-b7e9eda1dddd"
type = "Tracing"
prompt.program = """
fn main() {
  let mut v: Vec<i32> = vec![1, 2, 3];
  let mut v2: Vec<&mut i32> = Vec::new();
  for i in &mut v {
    v2.push(i);
  }
  *v2[0] = 5;

  let a = *v2[0];
  let b = v[0];
  println!("{a} {b}");
}
"""
answer.doesCompile = true
answer.stdout = "5 5"
context = """
`i` hat den Typ `&mut i32`, ist also ein Zeiger auf eine Zahl in `v`. Wenn wir `i` in `v2` einfügen, enthält `v2` also Zeiger in `v`. Daher
verändert eine Änderung von `v2[0]` tatsächlich `v[0]`.
"""