[[questions]]
id = "79942534-f414-41e6-944f-96d57905632c"
type = "MultipleChoice"
prompt.prompt = "Was ist der Unterschied zwischen `a + b` und `a.push_str(b)`, um zwei Strings zu verketten?"
answer.answer = "`+` verbraucht die Ownership von `a`, `push_str` dagegen nicht"
prompt.distractors = [
  "`push_str` ist zur Laufzeit effizienter als `+`",
  "`push_str` verbraucht die Ownership von `b`, `+` dagegen nicht",
  "Es gibt keinen Unterschied, beide sind Aliasse für dieselbe Funktion"
]
context = """
`push_str` nimmt `&mut self`, `+` dagegen `self`, also verbraucht `+` die Ownership und `push_str` nicht.
"""

[[questions]]
id = "f1ab2171-96f0-4380-b16d-9055a9a00415"
type = "ShortAnswer"
prompt.prompt = """
Wie viele Heap-Allokationen können in diesem Programm höchstens stattfinden? Gib deine Antwort in Ziffern an, z. B. 0 oder 1.

```
let s1 = String::from("tic");
let s2 = String::from("tac");
let s3 = String::from("toe");

let s = s1 + "-" + &s2 + "-" + &s3;
```
"""
answer.answer = "7"
context = """
Eine Allokation für jeden Aufruf von `String::from` und eine Allokation für jeden Aufruf von `+`.
"""
