[[questions]]
id = "8f9e0e79-f4a7-4056-b35e-f7ae65b78888"
type = "MultipleChoice"
prompt.prompt = "Welche dieser Aussagen beschreibt am besten, warum `File::open` ein `Result` und keine `Option` zurückgibt?"
answer.answer = "Weil `Result` darstellen kann, warum eine Operation fehlgeschlagen ist, und das Öffnen einer Datei aus vielen Gründen fehlschlagen kann"
prompt.distractors = [
  "Weil `Result` die Möglichkeit eines Fehlschlags darstellt, während `Option` keine Fehlschläge darstellen kann",
  "Weil `Result` zur Laufzeit weniger Bytes als `Option` braucht, um Fehlschläge darzustellen",
  "Weil `Result` Fehler genauso darstellt wie die zugrunde liegenden Systemaufrufe"
]
context = """
`Option` kann nur darstellen, *dass* eine Operation fehlgeschlagen ist, `Result` dagegen kann erklären, *warum* sie fehlgeschlagen ist.
"""