[[questions]]
id = "31c55174-3fdf-4a21-959c-bb4056def264"
type = "MultipleChoice"
prompt.prompt = """
Jemand entwirft in Rust eine Bibliothek zum Schreiben von Kommandozeilenschnittstellen. 
Als Teil dieser Bibliothek wird eine Funktion implementiert, die Kommandozeilen-Flags parst, die ein Benutzer angibt. 
Welche Implementierung wäre für diesen Anwendungsbereich am besten geeignet?

```
fn parse_flag_v1(flag: &str) -> Result<String, String> {
  match flag.strip_prefix("--") {
    Some(no_dash) => Ok(no_dash.to_string()),
    None => Err(format!("Invalid flag {flag}"))
  }
}

fn parse_flag_v2(flag: &str) -> String {
  match flag.strip_prefix("--") {
    Some(no_dash) => no_dash.to_string(),
    None => panic!("Invalid flag {flag}")
  }
}
```
"""
answer.answer = "`parse_flag_v1`"
prompt.distractors = [ "`parse_flag_v2`" ]
prompt.answerIndex = 0
context = """
Hier würde man wahrscheinlich einen *behebbaren* Fehler (das `Result`) verwenden wollen. Übergibt jemand der CLI ein falsch formatiertes Flag,
möchte die CLI-Bibliothek vielleicht zusätzliche Hilfe anbieten, etwa die möglichen Flags anzeigen. Ein Panic würde die Anwendung zwingen,
nur die Panic-Meldung anzuzeigen, und wäre vermutlich schlechter für die Benutzerfreundlichkeit.
"""
