[[questions]]
id = "18bf21e1-4e1a-4e98-861d-c7032710a8ad"
type = "ShortAnswer"
prompt.prompt = "Wie heißt die Umgebungsvariable, die du auf `1` setzen solltest, um den Backtrace eines Panics zu sehen?"
answer.answer = "RUST_BACKTRACE"
context = """
Du kannst zum Beispiel auf der Kommandozeile Folgendes ausführen: `RUST_BACKTRACE=1 cargo run`
"""

[[questions]]
id = "23cabd75-88f5-4ff8-8bf5-4bd4d1a9e64a"
type = "MultipleChoice"
prompt.prompt = "Was ist KEIN guter Grund, einen Panic zu verwenden?"
answer.answer = "Das Programm hat einen Fehlerzustand erreicht, der einer aufrufenden Funktion mitgeteilt werden sollte"
prompt.distractors = [
  "Das Programm ist im Begriff, eine gefährliche Operation auszuführen",
  "Das Programm soll die Ausführung so schnell wie möglich beenden",
  "Das Programm hat einen nicht behebbaren Fehlerzustand erreicht"
]
context = """
Ein Panic sollte nicht verwendet werden, um einen Fehlschlag *innerhalb* des Programms mitzuteilen. Standardmäßig wird angenommen, dass aufrufende Funktionen
nicht versuchen, Panics abzufangen.
"""