[[questions]]
id = "91fb1ec6-fb11-4b6f-88df-dbc921a4108f"
type = "MultipleChoice"
prompt.prompt = "Welcher Codeausschnitt gibt für einen beliebigen Ausdruck `e` vom Typ `Result<T, E>` am besten wieder, wie `e?` übersetzt wird?"
answer.answer = """
```
match e {
  Ok(x) => x,
  Err(err) => { return Err(err); }
}
```
  """
prompt.distractors = [
  """
```
if let Err(err) = e {
  return Err(err);
}
```
  """,
  """
```
e.unwrap()
```
  """,
  """
```
match e {
  Ok(x) => x,
  Err(err) => panic!("{err}")
}
```
  """,
]
context = """
Ist `e` ein `Result`, holt `e?` nach Möglichkeit den Wert aus dem `Ok` heraus und gibt andernfalls das `Err` aus der aktuellen Funktion zurück.
"""

[[questions]]
id = "0ea46358-f560-4d3e-85d2-a1806eb7c797"
type = "Tracing"
prompt.program = """
// assume hello.txt has the contents "will"

fn read_username_from_file() -> Option<String> {
  let mut username_file = File::open("hello.txt")?;
  let mut username = String::new();
  username_file.read_to_string(&mut username)?;
  Some(username)
}

fn main() {
  println!("{}", read_username_from_file().unwrap()); 
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
`File::open` gibt ein `Result` zurück, aber der Rückgabetyp von `read_username_from_file` erwartet eine `Option`. Daher ist es ungültig, den Operator `?`
zu verwenden, bevor das `Result` in eine `Option` umgewandelt wurde (z. B. mit der Methode `Result::ok`).
"""