[[questions]]
id = "0aad53ff-89d7-4d14-8e3d-c17809220252"
type = "ShortAnswer"
prompt.prompt = """
Stell dir vor, du verwendest eine Funktion eines Drittanbieters, deren Implementierung du nicht kennst, deren Typsignatur aber so aussieht:

```
fn mystery<T>(x: T) -> T {
  // ????
}
```

Dann rufst du `mystery` so auf:

```
let y = mystery(3);
```

Angenommen, `mystery` verwendet keinen unsicheren Code, dann muss der Wert von `y` folgender sein:
"""
answer.answer = "3"
context = """
Die einzige mögliche Funktion (ohne unsicheren Code) mit der Signatur `T -> T` ist die Identitätsfunktion:

```
fn mystery<T>(x: T) -> T {
  x
}
```

Die Funktion könnte natürlich einen Panic auslösen oder etwas ausgeben, aber der Rückgabewert kann nur die Eingabe sein. `mystery` weiß nicht,
welcher Typ `T` ist, also kann `mystery` keinen Wert vom Typ `T` erzeugen oder verändern.
Weitere Beispiele für diese Idee findest du in [Theorems for free!](https://dl.acm.org/doi/pdf/10.1145/99370.99404).

**3 ist wirklich die richtige Antwort! Wenn du mit der Antwort nicht einverstanden bist, reiche bitte keinen Fehlerbericht ein!**
"""

[[questions]]
id = "40ae0cfe-3567-4d05-b0d9-54d612a2d654"
type = "Tracing"
prompt.program = """
fn print_slice<T>(v: &[T]) {
  for x in v {
    println!("{x}");
  }
}

fn main() {
  print_slice(&[1, 2, 3]);
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
Ist ein Typ generisch (wie `T`), können wir nichts über ihn annehmen, auch nicht, dass er sich in einen String umwandeln lässt. Daher ist `println!("{x}")` ungültig,
weil `x: &T`.
"""


[[questions]]
id = "694bb2d0-f2e6-4b0b-a3e7-2d9f9e8b3d09"
type = "Tracing"
prompt.program = """
struct Point<T> { x: T, y: T }

impl Point<i32> {
  fn f(&self) -> &i32 { &self.y }
}

impl<T> Point<T> {
  fn f(&self) -> &T { &self.x }
}

fn main() {
  let p: Point<i32> = Point { x: 1, y: 2 };
  println!("{}", p.f());
}
"""
answer.doesCompile = false
answer.lineNumber = 8
context = """
Diese Definitionen von `f` stehen in Konflikt, und Rust kann nicht bestimmen, welches `f` beim Aufruf von `p.f()` verwendet werden soll. Daher ist das ein Compilerfehler.
"""
