[[questions]]
id = "8b7f93c3-efb0-44e2-a0ca-b45e35620b30"
type = "MultipleChoice"
prompt.prompt = "Welche Art von Programmierfehler soll eine Lifetime verhindern?"
answer.answer = "Eine Referenz auf ein Objekt verwenden, nachdem dessen Speicher freigegeben wurde"
prompt.distractors = [
  "Das Ergebnis einer Berechnung, die fehlschlagen kann, verwenden, bevor auf einen möglichen Fehler geprüft wurde",
  "Über die Grenzen eines Arrays hinaus indexieren (Pufferüberlauf)",
  "Nicht genug Speicher für ein Objekt allozieren"
]
context = """
Lifetimes helfen festzustellen, wie lange ein Objekt „lebt“ und ob Referenzen auf dieses Objekt länger leben als das Objekt selbst. 
"""

[[questions]]
id = "77cf924a-ece1-4119-a762-f5f03536b4e1"
type = "Tracing"
prompt.program = """
fn shortest<'a, 'b>(x: &'a str, y: &'b str) -> &'a str {
  if x.len() < y.len() {
    x
  } else {
    y
  }
}

fn main() {
  println!("{}", shortest("hello", "rust"));
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """
Wenn die Typsignatur besagt, dass die Funktion eine Referenz mit der Lifetime `'a` zurückgeben muss, wäre es ungültig,
eine Referenz mit einer anderen Lifetime '`b` zurückzugeben, hier also `y`.
"""
