[[questions]]
id = "a2a1546b-27bf-47d2-a1bc-86d777573f40"
type = "Tracing"
prompt.program = """
use std::fmt::Display;
fn displayable<T: Display>(t: T) -> impl Display { t }

fn main() {
  let s = String::from("hello");
  let mut s2 = displayable(s);
  s2.push_str(" world");
  println!("{s2}");
}
"""
answer.doesCompile = false
answer.lineNumber = 7
context = """
Da `displayable` `impl Display` zurückgibt, wissen wir nur, dass `s2` *irgendein* Typ ist, der `Display` implementiert, 
nicht aber, dass es ein `String` mit einer Methode `push_str` ist. Daher können wir `s2.push_str(..)` nicht aufrufen. Wäre der Rückgabetyp
von `displayable` `-> T`, würde dieses Programm kompilieren.
"""


[[questions]]
id = "8b35f91c-ced2-4b8f-bf1c-90550f2b744b"
type = "MultipleChoice"
prompt.prompt = """
Was ist die kleinste Menge von Trait-Bounds für `T`, mit der diese Funktion die Typprüfung besteht?
```
fn f<T: /* ??? */>(t: &T) {
  let t2 = t.clone();
  println!("{t2}");
}
```
"""
answer.answer = "`Clone + Display`"
prompt.distractors = [ "(keine Bounds)", "`Clone`", "`Clone + Display + Debug`" ]
context = """
Da `clone` aufgerufen wird und die Display-Klammern `{}` in einem Formatierer verwendet werden, muss `T` `Clone` und `Display` sein.
"""
