[[questions]]
id = "a91417cd-cd6d-416b-b72d-4af6b3fb2fd6"
type = "MultipleChoice"
prompt.prompt = """
Hat eine Referenz die Lifetime `'static`, bedeutet das:
"""
answer.answer = "Die Daten hinter der Referenz werden nie freigegeben"
prompt.distractors = [
  "Die Daten hinter der Referenz können nicht verändert werden",
  "Die Daten hinter der Referenz liegen im statischen Speicherbereich",
  "Die Daten hinter der Referenz sind nicht dynamisch"
]
context = """
`'static` bedeutet „lebt während des gesamten Programms“, daher dürfen Daten hinter einer statischen Referenz nie freigegeben werden. In der Praxis sind `'static`-Referenzen zwar
meist nicht veränderlich, aber die Bedeutung der Lifetime `'static` hat im Kern nichts mit Veränderlichkeit zu tun.
"""

[[questions]]
id = "e521409a-6cbd-48f5-bee0-7fa7f17cc562"
type = "MultipleChoice"
prompt.prompt = """
Betrachte die folgende nicht annotierte Funktionssignatur.

```
struct Foo<'a> {
  bar: &'a i32
}

fn baz(f: Foo) -> &i32 { /* ... */ }
```

Akzeptiert Rust diese Funktionssignatur? Wenn ja, welche Lifetimes leitet es ab?
"""
answer.answer = """
```
fn baz<'a>(f: Foo<'a>) -> &'a i32
```
  """
prompt.distractors = [
  "Rust weist diese Funktionssignatur zurück",
  """
```
fn baz(f: Foo) -> &i32
```
  """,
  """
```
fn baz<'a>(f: Foo<'a>) -> &i32
```
  """,
  """
```
fn baz<'a>(f: Foo) -> &'a i32
```
  """,

]
prompt.answerIndex = 4
context = """
Das Struct nimmt einen einzigen Lifetime-Parameter, und die Ausgabe hat eine einzige Lifetime, also nimmt Rust an, dass sie gleich sind.
"""

[[questions]]
id = "d03748df-8dcf-4ec8-bd30-341927544665"
type = "MultipleChoice"
prompt.prompt = """
Betrachte die folgende nicht annotierte Funktionssignatur.

```
struct Foo<'a> {
  bar: &'a i32
}

// Foo changed to &Foo
fn baz(f: &Foo) -> &i32 { /* ... */ }
```

Akzeptiert Rust diese Funktionssignatur? Wenn ja, welche Lifetimes leitet es ab?
"""
answer.answer = "Rust weist diese Funktionssignatur zurück"
prompt.distractors = [  
  """
```
fn baz(f: &Foo) -> &i32
```
  """,
  """
```
fn baz<'a>(f: &Foo<'a>) -> &'a i32
```
  """,
  """
```
fn baz<'a>(f: &'a Foo) -> &'a i32
```
  """,
  """
```
fn baz<'a, 'b>(f: &'a Foo<'b>) -> &'a i32
```
  """,
  """
```
fn baz<'a, 'b>(f: &'a Foo<'b>) -> &'b i32
```
  """
]
prompt.answerIndex = 0
context = """
Rust kompiliert dieses Programm nicht, weil mehrdeutig ist, ob die Lifetime der Ausgabe an
die Lifetime von `&Foo` oder an die der Referenz `Foo.bar` gebunden ist.
"""
