[[questions]]
id = "9ff33b87-38e2-471b-8ca4-9c31a6431376"
type = "MultipleChoice"
prompt.prompt = """
**Programm 1:**

```ide
/// Returns the n-th largest element in a slice
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```

Welche der folgenden Fehlermeldungen beschreibt am besten den Compilerfehler, den du beim Kompilieren dieses Programms bekommen würdest?
"""
answer.answer = "cannot borrow `elems` as mutable for `sort`"
prompt.distractors = [
  "cannot move out of shared reference for `clone`",
  "cannot move out of shared reference in expression `&elems[n]`",
  "the lifetime of `T` must outlive `&[T]`",
]
context = """
Die Methode `slice::sort` erwartet eine veränderliche Referenz auf einen Slice,
bekommt aber eine unveränderliche Referenz.
"""


[[questions]]
id = "3ee8d846-d282-4de1-8e83-5ca0bc44fc13"
type = "MultipleChoice"
prompt.prompt = """
**Programm 1:**

```ide
/// Returns the n-th largest element in a slice
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```

Wenn du versuchst, diese Funktion zu kompilieren, gibt der Compiler normalerweise folgenden Fehler aus:

```text
error[E0596]: cannot borrow `*elems` as mutable, as it is behind a `&` reference
 --> test.rs:3:5
  |
3 |     elems.sort();
  |     ^^^^^^^^^^^^ `elems` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```

Nimm an, der Compiler würde diese Funktion NICHT zurückweisen. Welche (falls überhaupt) der folgenden Programme würden
(1) den Compiler passieren und (2) bei der Ausführung möglicherweise undefiniertes Verhalten verursachen?
Wähle jedes Programm aus, das beide Kriterien erfüllt, ODER wähle „Keines dieser Programme“, wenn keines sie erfüllt.
"""
answer.answer = ["Keines dieser Programme"]
prompt.distractors = [
"""
```
let v = vec![5, 4, 3, 2, 1];
find_nth(&v, 10);
```
""",
"""
```
let v = vec![5, 4, 3, 2, 1];
find_nth(&v, 0);
println!("{}", v[0]);
```
""",
"""
```
let v = vec![5, 4, 3, 2, 1];
let n = &v[0];
find_nth(&v, 0);
println!("{}", n);
```
""",
]
context = """
Dieses Programm ist technisch speichersicher, weil `slice::sort` Elemente nur umherschieben,
aber nicht freigeben kann. So zeigt `&v[0]` nach dem Aufruf von `find_nth` garantiert auf 
*irgendeine* Zahl, auch wenn es nicht die *ursprüngliche* Zahl ist.

Beachte, dass `find_nth(&v, 10)` kein undefiniertes Verhalten verursacht, weil Rust Zugriffe auf Arrays
prüft; die Auswertung von `&v[10]` löst daher einen Panic aus.
"""


[[questions]]
id = "d070eb9e-4527-453a-8c9b-698739a3dd6a"
type = "MultipleChoice"
prompt.prompt = """
**Programm 1:**

```ide
/// Returns the n-th largest element in a slice
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```

Welche der folgenden Korrekturen (gelb hervorgehoben) erfüllt diese drei Kriterien am besten:
1. Die korrigierte Funktion besteht den Rust-Compiler,
2. die korrigierte Funktion bewahrt die Absicht des ursprünglichen Codes und
3. die korrigierte Funktion führt keine unnötigen Ineffizienzen ein?
"""
answer.answer = """
```ide
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    `[let mut elem_refs: Vec<&T> = elems.iter().collect();]`
    `[elem_refs.sort();]`
    let t = `[elem_refs[n]]`;
    return t.clone();
}
```
"""
prompt.distractors = [
"""
```ide
fn find_nth<T: Ord + Clone>(`[elems: &mut [T]]`, n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```
""",
"""
```ide
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    `[let mut elems = elems.to_vec();]`
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```
""",
"""
```ide
fn find_nth<`[T: Ord]`>(`[mut elems: Vec<T>]`, n: usize) -> T {
    elems.sort();
    let t = `[elems.remove(n)]`;
    return `[t]`;
}
```
""",
]
context = """
Eine Funktion wie `find_nth` ist offensichtlich als rein lesende Funktion gedacht, d. h., sie soll
eine Information über die Eingabefolge ermitteln. Jede Lösung, die die Eingabe verändert oder verwirft, bewahrt daher nicht die Absicht der ursprünglichen Funktion, selbst wenn
sie effizienter ist, als einen Hilfsvektor anzulegen. 

Einen `Vec<&T>` anzulegen ist besser, als einen `Vec<T>` anzulegen, denn wenn `T` groß ist, könnte
`elems.to_vec()` teuer sein. Wüssten wir dagegen, dass `T: Copy` gilt, wäre `to_vec`
vorzuziehen, um die Zahl der Zeiger-Dereferenzierungen in `elems.sort()` zu verringern.
"""

[[questions]]
id = "95979d75-5823-4059-a1cf-7e0eba69b41a"
type = "MultipleChoice"
prompt.prompt = """
**Programm 2:**

```ide
struct TestResult {
    /// Student's scores on a test
    scores: Vec<usize>,

    /// A possible value to curve all scores
    curve: Option<usize>
}
impl TestResult {  
    pub fn get_curve(&self) -> &Option<usize> { 
        &self.curve 
    }

    /// If there is a curve, then increments all 
    /// scores by the curve
    pub fn apply_curve(&mut self) {
        if let Some(curve) = self.get_curve() {
            for score in self.scores.iter_mut() {
                *score += *curve;
            }
        }
    }
}
```

Welche der folgenden Fehlermeldungen beschreibt am besten den Compilerfehler, den du beim Kompilieren dieses Programms bekommen würdest?
"""
answer.answer = "in `apply_curve`, cannot borrow `self.scores` as mutable for `iter_mut`"
prompt.distractors = [
  "in `get_curve`, cannot return a reference to a local variable `self.curve`",
  "in `apply_curve`, cannot borrow `self` as immutable for `get_curve`",
  "in `apply_curve`, `*score` cannot be mutated"
]
context = """
Wegen der Lifetime-Elision hat die Funktion `get_curve` die Typsignatur `get_curve<'a>(&'a self) -> &'a Option<usize>`. 
Das bedeutet, dass ein Aufruf von `self.get_curve()` die Ausleihe auf ganz `self` ausdehnt, nicht nur auf `self.curve`.
Daher ist `self` im Gültigkeitsbereich von `let Some(curve) = ...` unveränderlich ausgeliehen, und `self.scores.iter_mut()`
kann nicht aufgerufen werden.
"""


[[questions]]
id = "dcb42a15-d9b7-437d-95ec-f000b64ce277"
type = "MultipleChoice"
prompt.prompt = """
**Programm 2:**

```ide
struct TestResult {
    /// Student's scores on a test
    scores: Vec<usize>,

    /// A possible value to curve all scores
    curve: Option<usize>
}
impl TestResult {  
    pub fn get_curve(&self) -> &Option<usize> { 
        &self.curve 
    }

    /// If there is a curve, then increments all 
    /// scores by the curve
    pub fn apply_curve(&mut self) {
        if let Some(curve) = self.get_curve() {
            for score in self.scores.iter_mut() {
                *score += *curve;
            }
        }
    }
}
```

Wenn du versuchst, diese Funktion zu kompilieren, gibt der Compiler normalerweise folgenden Fehler aus:

```text
error[E0502]: cannot borrow `self.scores` as mutable because it is also borrowed as immutable
  --> test.rs:17:26
   |
16 |         if let Some(curve) = self.get_curve() {
   |                              ---------------- immutable borrow occurs here
17 |             for score in self.scores.iter_mut() {
   |                          ^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
18 |                 *score += *curve;
   |                           ------ immutable borrow later used here
```

Nimm an, der Compiler würde diese Funktion NICHT zurückweisen. Welche (falls überhaupt) der folgenden Programme würden
(1) den Compiler passieren und (2) bei der Ausführung möglicherweise undefiniertes Verhalten verursachen?
Wähle jedes Programm aus, das beide Kriterien erfüllt, ODER wähle „Keines dieser Programme“, wenn keines sie erfüllt.
"""
answer.answer = ["Keines dieser Programme"]
prompt.distractors = [
"""
```
let mut result = TestResult { 
    scores: vec![20, 50, 30], 
    curve: Some(10) 
};
result.apply_curve();
```
""",
"""
```
let mut result = TestResult { 
    scores: vec![20, 50, 30], 
    curve: Some(10) 
};
let x = &result.scores[0];
result.apply_curve();
println!("{}", x);
```
""",
"""
```
let mut result = TestResult { 
    scores: vec![20, 50, 30], 
    curve: Some(10) 
};
result.apply_curve();
println!("{:?}", result.scores);
```
""",
]
context = """
So wie es geschrieben ist, ist dieses Programm eigentlich sicher. Es ist eine Einschränkung des Borrow-Checkers, dass er nicht versteht, dass `get_curve`
nur `curve` ausleiht und `scores` nicht betrifft. Würde `get_curve` aber theoretisch so geändert, dass es eine Referenz
auf etwas in `self.scores` zurückgibt, könnte die Speichersicherheit möglicherweise verletzt werden.
"""

[[questions]]
id = "aa93c497-9864-4799-b69b-7de42c158f2a"
type = "MultipleChoice"
prompt.prompt = """
**Programm 2:**

```ide
struct TestResult {
    /// Student's scores on a test
    scores: Vec<usize>,

    /// A possible value to curve all scores
    curve: Option<usize>
}
impl TestResult {  
    pub fn get_curve(&self) -> &Option<usize> { 
        &self.curve 
    }

    /// If there is a curve, then increments all 
    /// scores by the curve
    pub fn apply_curve(&mut self) {
        if let Some(curve) = self.get_curve() {
            for score in self.scores.iter_mut() {
                *score += *curve;
            }
        }
    }
}
```

Welche der folgenden Korrekturen (gelb hervorgehoben) erfüllt diese drei Kriterien am besten:
1. Die korrigierte Funktion besteht den Rust-Compiler,
2. die korrigierte Funktion bewahrt die Absicht des ursprünglichen Codes und
3. die korrigierte Funktion führt keine unnötigen Ineffizienzen ein?
"""
answer.answer = """
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = `[self.curve]` {
        for score in self.scores.iter_mut() {
            *score += curve;
        }
    }
}
```
"""
prompt.distractors = [
"""
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = self.get_curve()`[.as_ref()]` {
        for score in self.scores.iter_mut() {
            *score += *curve;
        }
    }
}
```
""",
"""
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = self.get_curve() {
        for score in self.scores`[.clone()]`.iter_mut() {
            *score += *curve;
        }
    }
}
```
""",
"""
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = self.get_curve() {
        for score in self.scores`[.iter()]` {
            *score += *curve;
        }
    }
}
```
""",
]
context = """
Wird die Definition von `get_curve` in `apply_curve` eingesetzt (Inlining), versteht der Borrow-Checker, dass `self.curve` nicht `self.scores` ist,
und lässt die Funktion kompilieren. Das ist eine gängige Umgehung für diese Art von Einschränkung des Borrow-Checkers.

Eine andere Möglichkeit ist, auszunutzen, dass sich `self.curve` billig kopieren lässt, und [`Option::copied`](https://doc.rust-lang.org/std/option/enum.Option.html#method.copied) zu verwenden, 
was die Ausleihe von `self` aufhebt, sobald `.copied()` aufgerufen wird.
"""