[[questions]]
id = "c4adb1a8-ca6a-43c1-ae34-54302f674ece"
type = "Tracing"
prompt.program = """
trait MakeNoise {
  fn make_noise(&self) {
    println!("(silence)");
  }
}

struct Dog {}
struct Cat {}

impl MakeNoise for Dog {
  fn make_noise(&self) {
    println!("bark");
  }
}

impl MakeNoise for Cat {}

fn main() {
  let dog = Dog {};
  let cat = Cat {};
  dog.make_noise();
  cat.make_noise();
}
"""
answer.doesCompile = true
answer.stdout = "bark\n(silence)"
context = """
Die Implementierung von `MakeNoise` stellt für `Dog` eine spezifische Implementierung bereit und verwendet für `Cat` die Standardimplementierung.
Daher gibt der Aufruf von `make_noise` auf beiden `bark` bzw. `(silence)` aus. 
"""

[[questions]]
id = "783f2485-e5b9-483b-8368-064366c77285"
type = "MultipleChoice"
prompt.prompt = "Die folgenden Aussagen betreffen die Arten von Trait-Implementierungen, die Rust erlaubt. Wähle jede Aussage aus, die zutrifft."
prompt.distractors = ["Du kannst einen externen Trait für einen externen Typ implementieren"]
answer.answer = [
  "Du kannst einen externen Trait für einen lokalen Typ implementieren",
  "Du kannst einen lokalen Trait für einen externen Typ implementieren",
  "Du kannst einen lokalen Trait für einen lokalen Typ implementieren"
]
context = """
Die „Orphan-Rule“ verlangt, dass du keinen externen Trait für einen externen Typ implementieren kannst, 
damit Code nicht kaputtgeht, wenn zwei Crates widersprüchliche Implementierungen bereitstellen.
"""