[[questions]]
id = "7a7bb518-b06e-4756-9510-6a8d0d1c84fa"
type = "ShortAnswer"
prompt.prompt = "Welche Annotation fügst du einer Funktion hinzu, um anzuzeigen, dass sie ein Unit-Test ist?"
answer.answer = "#[test]"
context = """
Damit weiß das Test-Harness von Cargo, dass es die Funktion als Test und nicht als Bibliothekscode behandeln soll.
"""

[[questions]]
id = "cd77485f-723a-4978-8da6-c4ca3df44c44"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du hast eine Funktion mit dieser Typsignatur:

```
fn f(x: usize) -> Result<usize, String>;
```

Und du willst testen, dass `f(0)` `Err(_)` zurückgibt. 
Was ist KEINE gültige Möglichkeit, das zu testen?
"""
answer.answer = """
```
#[test]
#[should_err]
fn test() -> Result<usize, String> {
  f(0)
}
```
  """
prompt.distractors = [
  """
```
#[test]
fn test() {
  assert!(f(0).is_err());
}
```
  """,
  """
```
#[test]
#[should_panic]
fn test() { 
  f(0).unwrap();
}
```
  """,
  """
```
#[test]
fn test() {
  assert!(match f(0) {
    Ok(_) => false,
    Err(_) => true
  });  
}
```
  """
]
context = """
`should_err` gibt es in Rust nicht – jeder Test, der ein `Result` zurückgibt, muss `Ok` zurückgeben, um zu bestehen.
"""