[[questions]]
id = "3da96b29-d975-4cd8-a8eb-b1a6bd9b5c0a"
type = "MultipleChoice"
prompt.prompt = """
Was ist KEIN guter Grund, Unit-Tests in `#[cfg(test)] mod tests { ... }` zu verpacken?
"""
answer.answer = "Es gibt deinen Tests Zugriff auf private Funktionen"
prompt.distractors = [
  "Es kann die Größe der vom Compiler erzeugten Artefakte verringern",
  "Es kann die Kompilierzeiten verbessern",
  "Es trennt Test-Hilfsfunktionen vom Bibliothekscode"
]
context = """
Alle Unit-Tests in einer Datei haben Zugriff auf die privaten Funktionen dieser Datei, unabhängig davon, ob sie in einem `mod tests` stehen oder nicht.
"""