[[questions]]
id = "affe428d-0a8e-430b-9567-99e6b7563c0f"
type = "MultipleChoice"
prompt.prompt = """
Welche der folgenden Aktionen funktioniert möglicherweise nicht korrekt, wenn sie von mehreren Tests ausgeführt wird und `cargo test` ohne zusätzliche Konfiguration läuft?
"""
answer.answer = "Text in eine einzige Datei schreiben"
prompt.distractors = [
  "Strings auf stdout protokollieren",
  "Durch Panics fehlschlagen",
  "Daten aus einer einzigen Datenbank lesen"
]
context = """
Tests laufen standardmäßig parallel, daher können Aktionen, die nicht threadsicher sind (etwa das Schreiben in eine einzige Datei), eine Race-Condition verursachen.
"""

[[questions]]
id = "19e292f4-4bc4-4868-a58a-edf62c3e3b2a"
type = "ShortAnswer"
prompt.prompt = """
Betrachte ein Programm mit folgenden Unit-Tests:

```
#[test]
fn test_the_logger() { /* ... */ }

#[test]
fn test_the_database() { /* ... */ }

#[test]
fn test_logger_and_database() { /* ... */ }
```

Was ist der *kürzeste* String, den du `cargo test <the_string>` übergeben kannst, sodass *nur* `test_the_logger` und `test_the_database` ausgeführt werden?
"""
answer.answer = "h"
context = """
Der kürzeste Teilstring, der nicht in `test_logger_and_database`, aber in `test_the_logger` und `test_the_database` enthalten ist,
ist „h“ (das mittlere Zeichen von „the“).
"""