[[questions]]
id = "a055fa7c-89e2-467e-8458-62cbf3ffb8bf"
type = "Tracing"
prompt.program = """
fn main() {
    let mut s = String::from("Hello");
    let mut add_suffix = || s.push_str(" world");
    println!("{s}");
    add_suffix();
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """
`add_suffix` leiht `s` zwischen seiner Definition und seiner Verwendung veränderlich aus, daher ist das `println` (ein Lesen von `s`) ungültig.
"""

[[questions]]
id = "266d3cb3-de76-4b91-bd13-c3d6cb9e7fd7"
type = "Tracing"
prompt.program = """
fn main() {
    let mut s = String::from("Hello");
    let add_suffix = |s: &mut String| s.push_str(" world");
    println!("{s}");
    add_suffix(&mut s);
}
"""
answer.doesCompile = true
answer.stdout = "Hello"
context = """
Da `add_suffix` `s` nicht erfasst, ist es in Ordnung, `s` zu lesen, bevor es mit `add_suffix` verändert wird.
"""

[[questions]]
id = "0f298680-d870-47a1-962c-1c668f75cb68"
type = "MultipleChoice"
prompt.prompt = """
Betrachte folgende API:

```rust
/// Executes a function with a mutable reference to each element of a vector
fn for_each_mut<T, F: ___(&mut T)>(v: &mut Vec<T>, mut f: F) {
    for x in v.iter_mut() {
        f(x);
    }
}
```

Welcher der folgenden Funktions-Traits passt am besten in die Lücke?
"""
answer.answer = "`FnMut`"
prompt.distractors = ["`Fn`", "`FnOnce`"]
context = """
`f` wird mehrmals aufgerufen, daher passt `FnOnce` nicht. Sowohl `Fn` als auch `FnMut` können funktionieren, und `FnMut` ist weniger einschränkend, also passt `FnMut` am besten.
"""


[[questions]]
id = "65f574b1-b418-4abe-852e-8b14d88368a7"
type = "MultipleChoice"
prompt.prompt = """
Betrachte folgende API:

```rust
pub struct Analyzer<F> {
    postprocess: F
}

impl<F: ___(i32) -> i32> Analyzer<F> {
    fn process(&self, n: i32) -> i32 { /* .. */ }
    pub fn pipeline(&self, n: i32) -> i32 {
        let n = self.process(n);
        (self.postprocess)(n)
    }
}
```

Welcher der folgenden Funktions-Traits passt am besten in die Lücke?
"""
answer.answer = "`Fn`"
prompt.distractors = ["`FnMut`", "`FnOnce`"]
context = """
`pipeline` könnte mehrmals aufgerufen werden, daher passt `FnOnce` nicht.
`pipeline` nimmt eine unveränderliche Referenz auf `self`; wäre `postprocess` `FnMut`, könnte es innerhalb von `pipeline` nicht aufgerufen werden.
Daher passt hier `Fn` am besten.
"""