[[questions]]
id = "e6cbd582-9692-4045-a984-8770a12e1b95"
type = "MultipleChoice"
prompt.prompt = """
Was beschreibt am besten die Begründung dafür, dass Rust die Typen von Argumenten und Rückgabewerten bei Closures ableitet, bei Funktionen auf oberster Ebene aber nicht?
"""
answer.answer = "Funktionen auf oberster Ebene können Teil der externen Schnittstelle einer Bibliothek sein, Closures dagegen können nicht direkt offengelegt werden"
prompt.distractors = [
  "Wegen des Halteproblems ist es für Rust mathematisch unmöglich, die Typen von Funktionen auf oberster Ebene abzuleiten",
  "Wegen der Abwärtskompatibilität mit älteren Rust-Versionen",
  "Für alles, was sich einer Variable zuweisen lässt, kann der Typ abgeleitet werden, und Funktionen auf oberster Ebene lassen sich keiner Variable zuweisen"
]
context = """
Rust könnte theoretisch Typableitung für Funktionen auf oberster Ebene bieten. Funktionale Sprachen wie Haskell und OCaml haben dieses Feature.
Die Designer von Rust haben sich aber bewusst dafür entschieden, bei Funktionen auf oberster Ebene Typannotationen zu verlangen, um Klarheit auf 
der Ebene der Schnittstellen zu fördern: Eine Funktion hat immer genau den Typ, den sie angibt.
"""

[[questions]]
id = "f844d1c2-3f63-4cdb-b16e-6e818e996e0d"
type = "MultipleChoice"
prompt.prompt = """
Rust erlaubt Pattern-Matching in Closure-Argumenten, einschließlich des Unterstrichs. Du könntest zum Beispiel Folgendes schreiben:

```rust
let f = |_| (); // sometimes called the "toilet closure"
let s = String::from("Hello");
f(s);
```

Was beschreibt die Beziehung zwischen `f` und `s` in diesem Programm am besten?
"""
answer.answer = "`f` sorgt dafür, dass `s` sofort verworfen wird"
prompt.distractors = [
  "`f` hat keine Auswirkung auf `s`",
  "`f` liest `s` und wirft das Ergebnis dann weg",
  "`f` erfasst `s` in seiner Umgebung"
]
context = """
Die „Toilet Closure“ ähnelt [`std::mem::drop`](https://doc.rust-lang.org/std/mem/fn.drop.html), also einer Funktion, die
ein Argument verschiebt (*moves*) und dafür sorgt, dass es verworfen wird.
"""