[[questions]]
id = "d50dd9fb-f84c-4748-9e45-cd3dc8d5fb47"
type = "MultipleChoice"
prompt.prompt = """
Was beschreibt am besten, warum Iteratoren als „lazy“ (träge) bezeichnet werden?
"""
answer.answer = "Ein Iterator bewirkt nichts, bis du Methoden aufrufst, die Elemente aus dem Iterator holen"
prompt.distractors = [
    "Ein Iterator erstellt eine Kopie jedes Elements, über das er iteriert", 
    "Ein Iterator übernimmt die Ownership der Folge von Elementen, über die er iteriert", 
    "Ein Iterator iteriert nur über eine bestimmte Anzahl von Elementen"
]
context = """
„Lazy“ bedeutet im Allgemeinen „arbeitet erst, wenn man es dazu auffordert“, und Iteratoren führen keine Berechnung aus, bis
`Iterator::next` aufgerufen wird.
"""

[[questions]]
id = "19eac65e-44ad-4349-9632-47bdbb519d46"
type = "MultipleChoice"
prompt.prompt = """
Wahr oder falsch: Diese beiden Codeausschnitte sind semantisch gleichwertig, wobei `iter` ein Iterator ist.

Codeausschnitt 1:
```
while let Some(x) = iter.next() {
    f(x);
}
```

Codeausschnitt 2:
```
for x in iter {
    f(x);
}
```
"""
answer.answer = "Wahr"
prompt.distractors = ["Falsch"]
context = """
Die for-Schleife ist syntaktischer Zucker für `while let`, das selbst wiederum syntaktischer Zucker für `loop` und `break` ist.
"""

[[questions]]
id = "ff652580-b487-4379-bd70-652f5803321d"
type = "Tracing"
prompt.program = """
fn main() {
    let v = vec![1, 2, 3, 4];
    let a: Vec<_> = v.iter().filter(|x: &&i32| *x % 2 == 0).map(|x: &i32| x * 2).collect();
    let b: Vec<_> = v.iter().map(|x: &i32| x * 2).filter(|x: &i32| x % 2 == 0).collect();
    println!("{} {}", a[0], b[0]);
}
"""
answer.doesCompile = true
answer.stdout = "4 2"
context = """
Die Reihenfolge der Iteratoren spielt eine Rolle – ein filter und dann ein map ist nicht dasselbe wie ein map und dann ein filter!

Vielleicht fragst du dich, warum der erste filter `*x` verwendet und der zweite nicht. 
`v.iter()` erzeugt einen `Iterator<Item = &i32>`. Der Aufruf `.filter()` nimmt einen `Iterator<Item = T>` als Eingabe
und übergibt `&T` an sein Prädikat. Daher gilt in Zeile 3 `x: &&i32`. Die Standardbibliothek von Rust implementiert den
Restoperator `%` für `&i32` auf der linken Seite ([siehe Dokumentation](https://doc.rust-lang.org/std/ops/trait.Rem.html#impl-Rem%3Ci32%3E-for-%26'a+i32)),
aber nicht für `&&i32`. Also müssen wir `x` einmal dereferenzieren, um es im Ausdruck `*x % 2` zu verwenden.

In Zeile 4 dagegen übergibt `.map()`, wenn es einen `Iterator<Item = T>` als Eingabe nimmt, `T` an seine Closure.
Daher nimmt die Closure in `map` `&i32` als Eingabe. Der Multiplikationsoperator `*` ist für `&i32` implementiert,
also muss `x` in `x * 2` nicht dereferenziert werden. Die Operation `x * 2` erzeugt einen Wert vom Typ `i32`, also
ist das Ergebnis des map ein `Iterator<Item = i32>`. Der `filter` nimmt dann `x : &i32`, das für `x % 2` ebenfalls
nicht dereferenziert werden muss. Jetzt weißt du Bescheid!
"""
