[[questions]]
id = "20846719-fe7b-48b8-abfd-9c5f1174472f"
type = "MultipleChoice"
prompt.prompt = """
Betrachte einen Workspace mit folgender Struktur:

```
├── Cargo.lock
├── Cargo.toml
└── crates
    ├── a
    |   ├── lib.rs
    |   └── Cargo.toml
    └── b
        ├── lib.rs
        └── Cargo.toml
```

Die Dateien haben folgenden Inhalt:

```
// crates/b/lib.rs
pub fn f() {}
```

```toml
# crates/a/Cargo.toml
[dependencies]
b = {path = "../b"}
```

Welcher ist der richtige Pfad, um in `a/lib.rs` auf `f` zu verweisen?
"""
answer.answer = "`b::f`"
prompt.distractors = [
    "`crates::b::f`",
    "`workspace::b::f`",
    "`super::b::f`",
]
context = """
Aus Sicht von `a` ist `b` ein externes Crate wie jedes andere, daher verwendest du kein Präfix, um auf seine Elemente zuzugreifen.
"""

[[questions]]
id = "bc8a69b2-d9a8-4438-8657-391c3fda5ed9"
type = "ShortAnswer"
prompt.prompt = """
Betrachte einen Workspace mit drei Paketen `a`, `b` und `c`. Ihre Manifeste lauten:

```toml
# a/Cargo.toml
[dependencies]
rand = "0.8.4"

# b/Cargo.toml
[dependencies]
rand = "0.7.3"

# c/Cargo.toml
[dependencies]
rand = "0.8.5"
```

Wie viele verschiedene Versionen von `rand` werden beim Kompilieren aller Pakete im Workspace verwendet? 
Gib deine Antwort als Ziffer an, z. B. 0, 1 und so weiter.
"""
answer.answer = "2"
context = """
Nach den Regeln der semantischen Versionierung teilen sich `a` und `c` den neuesten Patch der Minor-Version `0.8`.
`b` verwendet den neuesten Patch der Minor-Version `0.7`. Insgesamt werden also zwei Versionen verwendet.
"""