[[questions]]
id = "e2df0a8a-7bdd-40a3-9918-e4a856978cbb"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du veröffentlichst eine Bibliothek und willst am Anfang der Datei `lib.rs` Dokumentation über die gesamte Bibliothek schreiben.
Der Dokumentation sollte folgende Kommentarsyntax vorangestellt werden:
"""
answer.answer = "`//!`"
prompt.distractors = [
    "`///`",
    "`//`",    
]
context = """
`//!` eignet sich für Dokumentation auf Modulebene, während `///` zum Dokumentieren einzelner Elemente wie Funktionen dient.
"""

[[questions]]
id = "cfb65011-0578-4032-8aaa-b346b091602b"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du erstellst eine Bibliothek `worldly` mit folgender Funktion in `lib.rs`:

    /// Adds the string "world" to `s`.
    ///
    /// # Example
    /// ```
    /// let mut s = String::new();
    /// worldly::add_world(&mut s);
    /// assert_eq!(s, "Hello world");
    /// ```
    pub fn add_world(s: &mut String) {
        s.push_str("world");
    }

    #[test]
    fn test_add_world() {
        let mut s = String::new();
        add_world(&mut s);
        assert_eq!(s, "world");
    }

Wenn du `cargo test` ausführst, schlägt dann ein Test fehl?
"""
answer.answer = "Ja"
prompt.distractors = [
    "Nein",    
]
context = """
Das fehlerhafte Beispiel wird als Dokumentationstest ausgeführt und lässt `cargo test` fehlschlagen.
"""