[[questions]]
id = "7e4eeb62-55c2-443b-a8cc-fba060501245"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, du veröffentlichst eine Bibliothek `foobar v0.1.0`. Nachdem du `cargo publish` ausgeführt hast, stellst du fest, dass eine
deiner Funktionen einen Bug hat. Was beschreibt am besten, wie du das veröffentlichte Crate in derselben Version `v0.1.0` überschreibst?
"""
answer.answer = "Es ist unmöglich, ein veröffentlichtes Crate in einer bestimmten Version zu überschreiben"
prompt.distractors = [
    "Füge dem Befehl `cargo publish` das Flag `--overwrite-published` hinzu",
    "Melde dich auf Crates.io an und lösche `v0.1.0` des veröffentlichten Crates",   
    "Führe `cargo yank` und dann `cargo publish` aus"
]
context = """
Crates.io erlaubt nicht, veröffentlichte Versionen zu überschreiben. In solchen Situationen ist es am besten, die fehlerhafte Version zurückzuziehen (*yank*)
und dann eine neue Version wie `v0.1.1` zu veröffentlichen.
"""

[[questions]]
id = "84ac16a8-2460-4baf-8913-06da6e3603e6"
type = "MultipleChoice"
prompt.prompt = """
Welcher der folgenden Schritte ist NICHT erforderlich, um ein Crate auf Crates.io zu veröffentlichen?
"""
answer.answer = "Jede öffentliche Funktion im Crate dokumentieren"
prompt.distractors = [
    "Im Abschnitt `[package]` von `Cargo.toml` eine Lizenz angeben",    
    "Sich auf Crates.io registrieren und anmelden",
    "Einen Crate-Namen wählen, der auf Crates.io noch nicht registriert ist"
]
context = """
Öffentliche Funktionen zu dokumentieren ist zwar empfehlenswert, aber standardmäßig nicht erforderlich. Beachte: Wenn Rust
undokumentierten Code als Fehler behandeln soll, kannst du an der Wurzel deiner Bibliothek folgende Anweisung hinzufügen:

```
#![deny(missing_docs)]
```
"""