[[questions]]
id = "8282968d-b1d3-42b4-b128-f97b951db4c6"
type = "Tracing"
prompt.program = """
struct Example(i32);
impl Drop for Example {
    fn drop(&mut self) {
        self.0 += 1;
        println!("drop {}", self.0);
    }
}
fn main() {
    let e = Example(0);
    drop(e);
    drop(e);
}
"""
answer.doesCompile = false
answer.lineNumber = 11
context = """
Ein besessener Wert kann nicht zweimal verworfen werden, daher ist es ein Compilerfehler, drop ein zweites Mal aufzurufen.
"""

[[questions]]
id = "b9121273-1c1e-4e99-9cff-a23f845aaeeb"
type = "MultipleChoice"
prompt.prompt = """
Betrachte diesen Codeausschnitt, der einen String alloziert:

```rust
fn main() {
    let mut s = String::new();
    ____
}
```

Welche der folgenden Operationen sind gültig, um die Lücke zu füllen, und würden dafür sorgen, dass `s` verworfen wird?
"""
answer.answer = ["`drop(s);`", "`(|_| ())(s);`", "`{ s };`"]
prompt.distractors = [
    "`s.drop();`",    
]
context = """
Jede Verwendung von `s`, die es verschiebt (*moves*) und das Ergebnis verwirft, sorgt dafür, dass `s` verworfen wird. `s.drop()` kann jedoch nicht
direkt aufgerufen werden.
"""