[[questions]]
id = "6f3c2a68-24f7-439b-9fe0-426abd27e487"
type = "Tracing"
prompt.program = """
fn main() {
    let mut n = 1;
    let b = Box::new(&mut n);
    **b += 1;
    println!("{}", n);
}
"""
answer.doesCompile = true
answer.stdout = "2"
context = """
Eine Box kann eine veränderliche Referenz enthalten, daher führt das zweifache Dereferenzieren von `b` zurück zu `n`.
"""

[[questions]]
id = "57595a80-c79f-4aae-a1d4-cdaf212d7c21"
type = "ShortAnswer"
prompt.prompt = """
Angenommen, wir haben ein Programm mit einer Variable:

```
let x: [Box<(usize, usize)>; 4] = /* ... */
```

Was ist bei einem Kompilierziel mit 64-Bit-Architektur die kleinstmögliche Größe von `x` im Speicher (in Bytes) auf dem Stack? 
Gib deine Antwort in Ziffern an, z. B. 0, 1 und so weiter.
"""
answer.answer = "32"
context = """
Eine Box enthält einen Zeiger, der auf einer 64-Bit-Architektur 8 Bytes groß ist. Ein Array aus 4 Zeigern ist daher mindestens 4 * 8 = 32 Bytes groß.
"""