[[questions]]
id = "e127342d-7ad2-4730-b930-774411e1872d"
type = "Tracing"
prompt.program = """
use std::rc::Rc;
fn main() {
    let n = Rc::new(1);
    let mut n2 = Rc::clone(&n);
    *n2 += 1;
    println!("{}", n);
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """
Daten in einem `Rc` können ohne innere Veränderlichkeit (siehe nächster Abschnitt) nicht verändert werden. `Rc` setzt das durch,
indem es den Trait `Deref` implementiert, aber nicht den Trait `DerefMut`.
"""

[[questions]]
id = "3b43eb45-3400-4555-b605-9ae1cde7c80c"
type = "Tracing"
prompt.program = """
use std::rc::Rc;
struct Example;
impl Drop for Example {
    fn drop(&mut self) {
        println!("drop");
    }
}
fn main() {
    let x = Rc::new(Example);    
    let y = Rc::clone(&x);    
    println!("A");
    drop(x);
    println!("B");
    drop(y);    
    println!("C");
}
"""
answer.doesCompile = true
answer.stdout = """
A
B
drop
C
"""
context = """
Der Wert in einem Zeiger mit Referenzzählung wird immer nur einmal verworfen, daher wird „drop“ nur einmal ausgegeben.
Das erste `drop(x)` verringert den Referenzzähler, verwirft den Wert aber nicht, weil `y` noch aktiv ist.
Beim Verwerfen von `y` stellt sich dann heraus, dass der Referenzzähler 0 ist, und `Example` wird verworfen.
"""