[[questions]]
id = "01904807-74c7-41ad-8d8b-cfb30e5ce10c"
type = "MultipleChoice"
prompt.prompt = """
Was beschreibt das Konzept der *inneren Veränderlichkeit* in Rust am besten?
"""
answer.answer = "Erlauben, dass Daten über eine unveränderliche Referenz verändert werden"
prompt.distractors = [
    "`unsafe`-Code in eine sichere API verpacken",
    "Erlauben, dass Daten im Inneren einer Datenstruktur verändert werden",
    "Mit dem Borrow-Checker zur Laufzeit Speichersicherheit durchsetzen"
]
context = """
Die Grundidee der inneren Veränderlichkeit ist, einen Wert vom Typ `&T` zu nehmen und 
Daten in `T` sicher verändern zu können.
"""

[[questions]]
id = "380cd865-76c5-419c-8961-af4c59d2ab71"
type = "MultipleChoice"
prompt.prompt = """
Betrachte eine API, die die Anzahl der Aufrufe einer bestimmten Methode zählt:

```
struct Api {
    count: ???
}

impl Api {
    fn some_method(&self) {
        // increment count
        // rest of the method...
    }    
}
```

Angenommen, der Zähler wird als `usize` dargestellt. Welcher der folgenden Wrapper-Typen wäre
in dieser Situation am besten geeignet?
"""
answer.answer = "`RefCell<usize>`"
prompt.distractors = [
    "`Rc<usize>`",
    "`Box<usize>`",
    "Keiner, `usize` genügt"
]
context = """
Hier ist eine `RefCell` nützlich, um ein internes Feld zu verändern, obwohl `some_method`
eine unveränderliche Referenz als Eingabe nimmt. Ist das interne Feld nur eine Ganzzahl, wäre `Cell<usize>`
oder `AtomicUsize` eine noch bessere Wahl.
"""

[[questions]]
id = "d4ae1b8e-79a7-4485-828f-fb30cdeb29d5"
type = "MultipleChoice"
prompt.prompt = """
Betrachte folgende fehlerhafte Implementierung einer `RefCell`, die nicht prüft,
ob der innere Wert ausgeliehen ist:

```
use std::cell::UnsafeCell;
struct BadRefCell<T>(UnsafeCell<T>);
impl<T> BadRefCell<T> {
    pub fn borrow_mut(&self) -> &mut T {
        unsafe { &mut *self.0.get() }
    }
}
```

Angenommen, wir haben eine `BadRefCell` wie diese:

```
let v = BadRefCell(UnsafeCell::new(vec![1, 2, 3]));
```

Welcher der folgenden Codeausschnitte würde mit dieser API die Speichersicherheit verletzen?
"""
answer.answer = """
```
let v1 = v.borrow_mut();
let n = &v1[0];
v.borrow_mut().push(0);
println!("{n}");
```
"""
prompt.distractors = [
"""
```
drop(v.borrow_mut());
drop(v.borrow_mut());
```
""",
"""
```
let v1 = v.borrow_mut();
let v2 = v.borrow_mut();
v1.push(0);
v2.push(0);
```
""",
"""
```
v.borrow_mut().push(0);
let n = v.borrow_mut()[0];
println!("{n}");
```
"""
]
context = """
Die `BadRefCell` erlaubt uns, gleichzeitig zwei veränderliche Referenzen auf die zugrunde liegenden Daten zu haben,
was eine Verletzung der Speichersicherheit ermöglicht, etwa einen Vektor neu zu allozieren, während eine Referenz auf seinen Inhalt gehalten wird.
"""