[[questions]]
id = "ceb96826-6c98-40e1-bff4-0bb61f35679d"
type = "MultipleChoice"
prompt.prompt = """
In manchen Nebenläufigkeits-APIs ist ein Mutex von den Daten getrennt, die er bewacht. Stell dir zum Beispiel eine hypothetische Mutex-API wie diese vor:

```
let mut data = Vec::new();
let mx: Mutex = Mutex::new();
{
    let _guard = mx.lock();
    data.push(0);
}
```

Was beschreibt am besten, warum Rust `Mutex<T>` statt einfach nur `Mutex` verwendet?
"""
answer.answer = "Um zu verhindern, dass auf die Daten eines Mutex zugegriffen wird, ohne den Mutex zu sperren"
prompt.distractors = [
    "Damit weniger Aufrufe von Mutex-Methoden nötig sind",
    "Um die Effizienz nebenläufiger Programme mit Mutexen zu verbessern",
    "Um zu verhindern, dass die Daten eines Mutex zwischen Threads verschoben werden"
]
context = """
Das Design von `Mutex<T>` stellt sicher, dass auf die Daten eines Mutex nur zugegriffen werden kann, wenn der Mutex gesperrt ist, und umgekehrt,
dass der Mutex entsperrt wird, sobald die Daten nicht mehr zugänglich sind.
"""

[[questions]]
id = "e5ac0c92-4694-4647-bd20-67825fe038b7"
type = "Tracing"
prompt.program = """
use std::{sync::Arc, thread};

fn main() {
    let s = String::from("Hello world");
    let a = Arc::new(&s);
    let a2 = Arc::clone(&a);
    let t = thread::spawn(move || a2.len());
    let len = t.join().unwrap();
    println!("{} {}", a, len);
}
"""
answer.doesCompile = false
answer.lineNumber = 7
context = """
Ein `Arc` ist trotzdem nicht sicher verwendbar, wenn seine Daten eine Referenz enthalten, denn die Referenz könnte (theoretisch)
ungültig werden, bevor alle Threads, die den `Arc` enthalten, fertig ausgeführt sind.
"""