[[questions]]
id = "43081862-aac8-4e18-9c55-1107ea4c7cc1"
type = "MultipleChoice"
prompt.prompt = """
Stell dir vor, du entwirfst eine API für eine Datenbankverbindung wie diese:

```
struct DbConnection { /* ... */ }
impl DbConnection {
    fn query(&self) -> DbResult {
        /* ... */
    }
}
```

Deine Datenbank unterstützt keine nebenläufigen Abfragen über dieselbe Verbindung. 
Welche der folgenden Marker-Traits sollte `DbConnection` implementieren?
"""
answer.answer = "`Send`"
prompt.distractors = [
    "`Send` und `Sync`",
    "`Sync`",
    "Weder `Send` noch `Sync`"
]
context = """
Eine `DbConnection` zwischen Threads zu senden, ist in Ordnung, daher sollte `DbConnection` `Send` implementieren.
Es wäre aber z. B. nicht zulässig, einen `Arc<Database>` so zu teilen, dass mehrere Threads nebenläufig
`db.query()` aufrufen, daher sollte `DbConnection` `Sync` nicht implementieren.
"""