[[questions]]
id = "a4680619-9533-4cbb-a785-7b73570168af"
type = "MultipleChoice"
prompt.prompt = """
Welche der folgenden Aspekte der objektorientierten Programmierung implementiert Rust?
"""
answer.answer = [
    "Objekte mit Methoden",
    "Kapselung privater Daten",
]
prompt.distractors = [
    "Vererbung von Methoden der Oberklasse"
]
context = """
Rust hat Objekte (d. h. Structs) und Kapselung (über das Schlüsselwort `pub`), aber keine Vererbung.
"""