
[[questions]]
id = "5d60cfc4-6377-48e7-96e4-fe1de0b0904e"
type = "Tracing"
prompt.program = """
use std::fmt::Debug;
fn main() {
    let n = 1;
    let s = String::from("Hello");
    let v: Vec<&dyn Debug> = vec![&n, &s];
    let n_ref = v[0] as &i32;
    println!("{}", n_ref + 1);
}
"""
answer.doesCompile = false
answer.lineNumber = 6
context = """
Anders als in manchen OOP-Sprachen kann ein Trait-Objekt nicht in einen konkreteren Typ „herabgecastet“ (*downcast*) werden
(außer im Fall des Traits [`Any`](https://doc.rust-lang.org/std/any/index.html)).
"""

[[questions]]
id = "cce62358-5291-4eb3-84d6-fbc570873ee3"
type = "MultipleChoice"
prompt.prompt = """
Stell dir vor, du implementierst eine generische Funktion auf zwei Arten:

```
fn f_opt1<T: SomeTrait>(t: &T) { /* ... */ }
fn f_opt2(t: &dyn SomeTrait) { /* ... */ }
```

Welche der folgenden Gründe sprechen in den meisten Fällen dafür, die Version mit Trait-Objekt (`f_opt2`) der typparametrischen Version (`f_opt1`) vorzuziehen?
Wähle alle zutreffenden aus.
"""
answer.answer = ["Kürzere Kompilierzeiten", "Kleinere Binärdatei"]
prompt.distractors = [
    "Bessere Laufzeit-Performance",
    "Bessere Ergonomie für Entwickler"
]
context = """
Weil die Monomorphisierung entfällt, lassen sich Funktionen mit Trait-Objekten schneller kompilieren und erzeugen kleinere Binärdateien. Das geht jedoch
meist auf Kosten der Laufzeit-Performance. Für Entwickler sind Trait-Objekte selten einfacher zu handhaben als Generics mit Trait-Bounds.
"""