[[questions]]
id = "d19f9e83-d4c2-41d5-9fc7-81db5135eb1e"
type = "MultipleChoice"
prompt.prompt = """
Im durchgehenden Beispiel dieses Abschnitts konnte ein Blogbeitrag einen von drei Zuständen haben: `Draft`, `PendingReview` und `Published`. Im Beispiel wurde jeder Zustand als Struct dargestellt, und Zustandsübergänge wurden als Trait-Methoden dargestellt, die Trait-Objekte zurückgeben.

Eine alternative Implementierung könnte die Zustände als Enum darstellen, etwa so:

```
enum BlogState {
    Draft,
    PendingReview,
    Published
}

impl Post {
    fn request_review(&mut self) {
        use BlogState::*;
        self.state = match self.state {
            Draft => PendingReview,
            PendingReview => PendingReview,
            Published => Published
        }
    }
}
```

Welche der folgenden Gründe sprechen dafür, die Darstellung mit Structs/Traits der Darstellung mit einem Enum vorzuziehen?
"""
answer.answer = [
    "Ein Nutzer der API könnte dem System einen neuen Zustand hinzufügen",
    "Das Hinzufügen eines neuen Zustands erfordert keine Änderung der Methoden aller anderen Zustände"
]
prompt.distractors = [
    "`match` ist zur Laufzeit langsamer als dynamischer Dispatch",
    "Ein Nutzer der API könnte für alle Zustände im System eine neue Methode hinzufügen"
]
context = """
Der Ansatz mit Structs/Traits ist in dem Sinne erweiterbar, dass ein Nutzer der API potenziell
einen neuen Zustand (etwa `Retracted`) erstellen könnte, ohne die Kernfunktionalität der API zu ändern. Beim
Hinzufügen dieses Zustands müssen die Methoden der anderen Zustände nicht geändert werden. Bei Enums dagegen
kann ein Nutzer dem Enum keinen neuen Zweig hinzufügen. Außerdem müssen alle `match`-Ausdrücke aktualisiert werden,
wenn ein Zustand hinzugefügt wird.

Ein `match` ist wahrscheinlich nicht langsamer als dynamischer Dispatch. Ein match ist eine einfache Verzweigung anhand
des Tags eines Enums, während dynamischer Dispatch eine Ebene der Indirektion über die virtuelle Tabelle (vtable) eines
Trait-Objekts mit nicht geinlinten Funktionsaufrufen erfordert.

Ein Nutzer der API kann beim Ansatz mit Structs/Traits für bestehende Zustände keine neue *Methode* hinzufügen,
sondern nur neue Zustände. Die Methoden sind durch die Trait-Definition des API-Autors festgelegt. Beachte, dass du über Erweiterungs-Traits eine neue Methode hinzufügen könntest, die nur auf bestehenden Methoden aufbaut, etwa so:

```
trait StateExt {
    fn request_review_twice(self: Box<Self>) -> Box<dyn State>;
}

impl<S: State> StateExt for S {
    fn request_review_twice(self: Box<Self>) -> Box<dyn State> {
        self.request_review().request_review()
    }
}
```

Diese Erweiterungen können aber nicht auf die privaten Daten der Zustände zugreifen.
"""