[multipart]
q = """
**Kontext:** Du entwirfst eine Serialisierungsbibliothek, die Rust-Datentypen in Formate wie JSON umwandelt.

**Funktionalität:** Ein Trait `Serialize`, der von serialisierbaren Typen implementiert werden kann, und eine Funktion `to_json`, die serialisierbare Typen in JSON umwandelt.

**Designs:** Unten stehen mehrere vorgeschlagene Designs, um die Funktionalität zu implementieren.

```
// Option 1: types serialize to a `Value` enum
pub enum Value {
	String(String),
	Number(isize)
}

pub trait Serialize {
	fn serialize(&self) -> Value;
}

fn value_to_json(value: Value) -> String {
	/* .. */
}

pub fn to_json(data: impl Serialize) -> String {
    let value = data.serialize();
    value_to_json(value)
}


// Option 2: types serialize via calls to a `Serializer` interface
pub trait Serialize {
	fn serialize<S: Serializer>(&self, serializer: &mut S);
}

pub trait Serializer {
	fn serialize_string(&mut self, s: &str);
	fn serialize_number(&mut self, n: isize);
}

struct JsonSerializer { buffer: String };
impl Serializer for JsonSerializer {
	/* .. */
}

pub fn to_json(data: impl Serialize) -> String {
	let mut serializer = JsonSerializer { buffer: String::new() };
	data.serialize(&mut serializer);
	serializer.buffer
}
```
"""

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Wähle jede Design-Option aus, die die folgende Anforderung erfüllt:

**Anforderung:** Es soll möglich sein, ein neues Datenformat hinzuzufügen, ohne Code in bestehenden Implementierungen des Traits `Serialize` ändern zu müssen.
"""
prompt.distractors = []
prompt.sortAnswers = true
answer.answer = ["1", "2"]
context = """
Beide Designs sind ausreichend entkoppelt, sodass jedes neue Datenformat unabhängig von allen `Serialize`-Implementierungen ist. Bei Option 1
wandelt jedes Datenformat einen `Value` in die Darstellung des Formats um. `Value` dient als Modulgrenze.

Bei Option 2 gibt es keine explizite Zwischendarstellung eines serialisierten Werts, stattdessen ist jede `Serialize`-Implementierung explizit generisch
über jede Wahl von `S`, die `Serializer` implementiert.
"""
id = "66e036c9-91a0-4611-8110-967b5ed1a514"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Wähle jede Design-Option aus, die die folgende Anforderung erfüllt:

**Anforderung:** Der Serialisierungsvorgang soll so wenig Speicher wie möglich verbrauchen.
"""
prompt.distractors = ["1"]
prompt.sortAnswers = true
answer.answer = ["2"]
context = """
Option 1 serialisiert Daten, indem sie eine Datenstruktur zuerst in eine Zwischendarstellung, `Value`, umwandelt und dann `Value` in das endgültige Format.
Diese Zwischendatenstruktur verbraucht Speicher, der bei Option 2 nicht benötigt wird, wo Daten direkt in das endgültige Format umgewandelt werden.
"""
id = "eaa95520-1b72-4f7d-a600-5444b6368785"


[[questions]]
multipart = "q"
type = "MultipleChoice"
prompt.prompt = """
Wähle jede Design-Option aus, die die folgende Anforderung erfüllt:

**Anforderung:** Wenn derselbe Datentyp in mehrere Formate serialisiert wird, soll das die Größe der kompilierten Binärdatei so wenig wie möglich erhöhen.
"""
prompt.distractors = ["2"]
prompt.sortAnswers = true
answer.answer = ["1"]
context = """
Bei Option 1 gibt es nur eine einzige Instanziierung von `Serialize`, die einen Typ `T` in einen `Value` umwandelt. Weil Option 2 generisch über Serialisierer `S` ist,
erzeugt der Rust-Compiler jedes Mal, wenn `T::serialize` mit einem neuen `S` aufgerufen wird, durch Monomorphisierung eine neue Instanz von `T::serialize`, was die Größe
der Binärdatei im Vergleich zu Option 1 erhöhen würde.
"""
id = "2751731e-7d18-46a1-aaea-b5734bf51c80"
