[multipart]
q = """
**Kontext:** Du entwirfst ein einfaches Ereignissystem, das als Reaktion auf Ereignisse Callback-Funktionen aufruft.

**Funktionalität:** Ein Struct `Events` stellt Funktionen bereit, um Callbacks zu registrieren.
Ein Callback ist entweder parallelisierbar (über mehrere Threads hinweg ausführbar) oder sequenziell (darf nur auf dem Haupt-Thread ausgeführt werden).

**Designs:** Unten stehen mehrere vorgeschlagene Designs, um die Funktionalität zu implementieren.

```
pub struct Events {
	// ...
}

// Option 1: parallel and sequential are two separate methods
impl Events {
	pub fn register<E, F: Fn(E)>(&mut self, f: F) { /* .. */ }
	pub fn register_sequential<E, F: Fn(E)>(&mut self, f: F) { /* .. */ }
}

// Option 2: parallel and sequential are two members of an enum
pub enum Callback<F> {
	Parallel(F),
	Sequential(F)
}
impl Events {
	pub fn register<E, F: Fn(E)>(&mut self, f: Callback<F>) { /* .. */ }
}

// Option 3: parallel and sequential are markers in a trait method
pub trait Register<Marker, F, E> {
	fn register(&mut self, f: F);
}
pub struct Parallel;
pub struct Sequential;
impl<F, E> Register<Parallel, F, E> for Events 
where F: Fn(E) {
	fn register(&mut self, f: F) { /* .. */ }
}
impl<F, E> Register<Sequential, F, E> for Events 
where F: Fn(Sequential, E) {
	fn register(&mut self, f: F) { /* .. */ }
}
```
"""

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Wähle jede Design-Option aus, die die folgende Anforderung erfüllt:

**Anforderung:** Ein Callback soll standardmäßig als parallelisierbar gelten, und die API soll dieses Standardverhalten widerspiegeln.
"""
prompt.distractors = ["2"]
prompt.sortAnswers = true
answer.answer = ["1", "3"]
context = """
Stellen wir uns zunächst vor, wie die Registrierung eines Callbacks bei jedem Design aussehen würde.

```rust
// Option 1
events.register(|e: OnClick| { /* .. */ });
events.register_sequential(|e: OnClick| { /* .. */ })

// Option 2
events.register(Callback::Parallel(|e: OnClick| { /* .. */ }));
events.register(Callback::Sequential(|e: OnClick| { /* .. */ }));

// Option 3
events.register(|e: OnClick| { /* .. */ });
events.register(|_: Sequential, e: OnClick| { /* .. */ });
```

Von diesen Optionen vermitteln die Optionen 1 und 3, dass parallel der Standardmodus ist, weil er der einfachsten Variante entspricht.
Für sequenzielle Ausführung braucht man entweder einen längeren Methodennamen (`_sequential`) oder einen Marker-Typ (`_: Sequential)`.

Option 2 kennzeichnet nicht klar, dass parallel der Standard sein soll, weil sowohl `Parallel` als auch `Sequential` an
`register` übergeben werden müssen.
"""
id = "4a32bad8-fee7-45b5-80ef-775d059aab48"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Wähle jede Design-Option aus, die die folgende Anforderung erfüllt:

**Anforderung:** Die API soll so wenige Methoden wie möglich exportieren.
"""
prompt.distractors = ["1"]
prompt.sortAnswers = true
answer.answer = ["2", "3"]
context = """
Die Optionen 2 und 3 exportieren nur eine einzige Methode `register`. Option 1 erfordert den Export zweier unterschiedlich benannter Registrierungsmethoden.
"""
id = "eaeafdad-ac3a-4d92-85eb-995991a81c2d"


[[questions]]
multipart = "q"
type = "MultipleChoice"
prompt.prompt = """
Wähle jede Design-Option aus, die die folgende Anforderung erfüllt:

**Anforderung:** Die API soll sich so wenig wie möglich auf die Typinferenz des Compilers stützen.
"""
prompt.distractors = ["3"]
prompt.sortAnswers = true
answer.answer = ["1", "2"]
context = """
Die Optionen 1 und 2 erfordern kaum Typinferenz über die Bestimmung des Typs der Funktion `F` hinaus.

Option 3 verwendet einen Trick zum Überladen, indem sie einen Trait `Register` erstellt, der über einen „Marker“-Typ parametrisiert ist.
Erinnere dich an ihre beiden Registrierungsaufrufe:
```
events.register(|e: OnClick| { /* .. */ })
events.register(|_: Sequential, e: OnClick| { /* .. */ })
```

Diese sehen aus, als würden sie dieselbe Implementierung verwenden, beziehen sich aber tatsächlich auf verschiedene Implementierungen derselben Methode.
Diese Implementierung verlässt sich darauf, dass der Compiler den Typ von `Marker` ableitet, wenn er auflöst, welcher Implementierung von `Register`
jeder Aufruf von `.register(..)` entspricht. Wenn unser Ziel also ist, uns *nicht* auf Typinferenz zu verlassen, ist Option 3 ungeeignet.
"""
id = "e0c4f766-b82a-496a-b669-ea9e0a367af7"