[[questions]]
id = "5dcd923f-13a4-4181-b252-4b580547249f"
type = "Tracing"
prompt.program = """
fn main() {
    let x = (0, 1);
    match x {
        (_, y) if y == 0 => println!("A"),
        (0, _) => println!("B"),
        _ => println!("C")
    }
}
"""
answer.doesCompile = true
answer.stdout = "B"
context = """
Der erste Zweig gleicht `y = 1` ab, also gilt `y != 0`, und das Pattern schlägt fehl.
Der zweite Zweig verlangt, dass `x == 0` gilt, was wahr ist, also passt das Pattern.
"""

[[questions]]
id = "ac0045c7-981a-46cb-baeb-adaa533804ad"
type = "MultipleChoice"
prompt.prompt = """
Betrachte das folgende Programm:

```
let a = [(0, 1)];
let ?? = a;
```

Welche der folgenden Patterns sind gültig und könnten den Platzhalter `??` ersetzen?
"""
answer.answer = [
    "`_`",
    "`[(n, ..)]`",
    "`[..]`"
]
prompt.distractors = [
    "`(_, n)`"
]
context = """ 
Das Pattern `(_, n)` ist nicht gültig, weil `a` ein Array von Tupeln ist und selbst kein Tupel.
"""

[[questions]]
id = "0b0d90c3-c81b-4b81-9e1b-f8bd58a22c6c"
type = "Tracing"
prompt.program = """
fn main() {
    let x = Some(&[0, 1]);
    match x {
        Some(&[.., 1, ..]) => println!("A"),
        Some(&[0, 1]) | None => println!("B"),
        _ => println!("C")
    }
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
Es ist nicht gültig, `..` auf beiden Seiten eines Werts zu verwenden, da dann mehrdeutig ist, welches
Array-Element gemeint ist.
"""

[[questions]]
id = "a7d38ffa-66b2-472a-90a5-b026b28ad3df"
type = "MultipleChoice"
prompt.prompt = """
Angenommen, wir haben einen Typ `Point` mit folgender Definition:

```
struct Point {
    x: i32,
    y: i32
}
```

Gegeben ist das folgende Pattern:

```
Point { x: x @ 0 ..= 5, y } if x + y != 0
```

Welche der folgenden Werte passen auf dieses Pattern?
"""
answer.answer = [
    "`Point { x: 5, y: -4 }`",
    "`Point { x: 0, y: 1 }`",
]
prompt.distractors = [
    "`Point { x: -1, y: 2 }`",
    "`Point { x: 3, y: -3 }`"
]
context = """
Dieses Pattern legt fest, dass `x` zwischen 0 und 5 (einschließlich) liegen muss und dass `x + y != 0` gilt.
Daher sind `(5, -4)` und `(0, 1)` gültig, `(-1, 2)` und `(3, -3)` dagegen nicht.
"""
