[[questions]]
id = "35e59c95-3d83-4277-8d88-a1986f4086d7"
type = "MultipleChoice"
prompt.prompt = """
Betrachte Pattern-Matching auf einen Ausdruck eines Typs `T`.
Welche dieser Aussagen beschreibt den Unterschied zwischen einem abweisbaren (*refutable*) und einem unabweisbaren (*irrefutable*) Pattern am besten?
"""
answer.answer = "Abweisbare Patterns passen auf mindestens einen Wert vom Typ `T` nicht, während unabweisbare Patterns auf alle Werte vom Typ `T` passen"
prompt.distractors = [
    "Abweisbare Patterns passen auf manche Werte eines anderen Typs `S`, während unabweisbare Patterns nur auf Werte vom Typ `T` passen",
    "Abweisbare Patterns passen auf keinen Wert vom Typ `T`, während unabweisbare Patterns auf manche Werte vom Typ `T` passen",
    "Abweisbare Patterns sind Patterns, bei denen `T` ein Enum ist, während unabweisbare Patterns Patterns sind, bei denen `T` kein Enum ist"
]
context = """
Ein Pattern ist abweisbar, wenn es einen Wert des erwarteten Typs gibt, auf den das Pattern nicht passt.
"""

[[questions]]
id = "3c29eb2d-cbe9-4a2c-99b8-aa5c6467c8b4"
type = "MultipleChoice"
prompt.prompt = """
Betrachte das folgende Programm:

```
let x: &[(i32, i32)] = &[(0, 1)];
```

Welche der folgenden Patterns sind für `x` **abweisbar**?
"""
answer.answer = [
    "`&[(x, y)]`",
    "`&[(x, y), ..]`",    
]
prompt.distractors = [
    "`&[..]`",
    "`_`"
]
context = """ 
Ein Slice hat keine feste Länge, daher ist jedes Pattern abweisbar, das voraussetzt,
dass `x` mindestens ein Element haben muss.
"""
