[[questions]]
id = "7859b06e-72ba-4c07-a3e2-b4f8cb7fd903"
type = "MultipleChoice"
prompt.prompt = """
Erinnere dich an die Definition des Traits `Add`:

```
trait Add<Rhs=Self> {
    type Output;
    fn add(self, rhs: Rhs) -> Self::Output;
}
```

Welche der folgenden Aussagen beschreibt am besten, warum `Output` ein assoziierter Typ ist, `Rhs` dagegen ein Typparameter?
"""
answer.answer = "Ein Typ `T` soll sich zu vielen anderen Typen `S` addieren lassen, aber eine gegebene Operation `T + S` soll immer genau einen Ausgabetyp haben"
prompt.distractors = [
    "Die Additionsoperation nimmt `Rhs` als Eingabe und erzeugt `Output` als Ausgabe, und Typparameter werden für Eingaben verwendet, assoziierte Typen dagegen für Ausgaben",
    "Ein Trait kann nur einen einzigen assoziierten Typ haben, daher muss `Rhs` ein Typparameter von `Add` sein",
    "Ein assoziierter Typ kann keinen Standardwert haben, ein Typparameter eines Traits dagegen schon"
]
context = """
Es stimmt, dass ein assoziierter Typ derzeit keinen Standardwert haben kann, aber das ist nicht der Hauptgrund
dafür, dass `Rhs` im Trait `Add` ein Typparameter ist.
"""

[[questions]]
id = "d2c77d93-3887-40a2-b93a-501aa315d676"
type = "MultipleChoice"
prompt.prompt = """
Erinnere dich an die Definition des Traits `Add`:

```
trait Add<Rhs=Self> {
    type Output;
    fn add(self, rhs: Rhs) -> Self::Output;
}
```

Welche der folgenden Aussagen beschreibt am besten, warum `Rhs` ein Typparameter des Traits `Add` und nicht der Funktion `add` ist? Das heißt, warum ist `Add` nicht so entworfen:

```
trait Add {
    type Output;
    fn add<Rhs>(self, rhs: Rhs) -> Self::Output;
}
```
"""
answer.answer = "Wäre `Rhs` ein Typparameter auf Funktionsebene, könnte die Definition von `add` keinerlei Struktur von `Rhs` voraussetzen"
prompt.distractors = [
    "Die Typprüfung läuft effizienter, wenn `Rhs` ein Typparameter auf Trait-Ebene statt auf Funktionsebene ist",
    "`Rhs` kann als Typparameter auf Funktionsebene keinen Standardtyp haben",
    "Die Codegenerierung für die Funktion `add` würde wegen des Typparameters auf Funktionsebene zusätzliche Zeit für die Monomorphisierung erfordern"
]
context = """
Ein solches Design wäre nicht sehr sinnvoll, weil `add<Rhs>` keinerlei Informationen über
die Struktur von `Rhs` hätte, sodass es unmöglich wäre, auf diese Weise eine sinnvolle Additionsfunktion zu implementieren.
"""

[[questions]]
id = "79db9ca4-693f-4e62-8b8d-356b51a63006"
type = "Tracing"
prompt.program = """
mod inner {
    pub trait A {
        fn f(&self) -> usize { 0 }
    }
    pub trait B {
        fn f(&self) -> usize { 1 }
    }
    pub struct P;
    impl A for P {}
    impl B for P {}
}
fn main() {
    use inner::{P, B};    
    println!("{}", P.f());    
}
"""
answer.doesCompile = true
answer.stdout = "1"
context = """
Wenn nur eine von zwei kollidierenden Trait-Implementierungen importiert wird, verwendet Rust die importierte
Implementierung. Vollständig qualifizierte Syntax ist hier nicht nötig.
"""

[[questions]]
id = "cb7e4d54-e95b-4153-99d6-e8f380e4f8b4"
type = "MultipleChoice"
prompt.prompt = """
Stell dir vor, du implementierst einen Trait `Trait` für einen Typ `T`. In welcher der folgenden Situationen
musst du `T` in einen Newtype hüllen?
"""
answer.answer = [
    "`Trait` ist in einem externen Crate definiert und `T` ist in einem externen Crate definiert",
]
prompt.distractors = [
    "`Trait` ist im lokalen Crate definiert und `T` ist in einem externen Crate definiert",
    "`Trait` ist in einem externen Crate definiert und `T` ist im lokalen Crate definiert",
    "`Trait` ist im lokalen Crate definiert und `T` ist im lokalen Crate definiert",
]
context = """
Die Orphan-Rule schreibt vor, dass ein Trait nicht für einen Typ implementiert werden kann, wenn beide
in einem externen Crate definiert sind, weshalb ein Newtype nötig ist. Wenn entweder der Trait oder der Typ
lokal definiert ist, ist kein Newtype nötig.
"""
