[[questions]]
id = "8c80f9e8-2d95-43cc-9aa4-04d617dd8cb9"
type = "Tracing"
prompt.program = """
macro_rules! manylet {
    ( $( $i:ident ),* = $e:expr ) => {
        $(
            let mut $i = $e;
        )*
    }
}

fn main() {
    let mut s = String::from("A");
    manylet!(x, y = s);
    x.push_str("B");
    println!("{x}{y}");
}
"""
answer.doesCompile = false
answer.lineNumber = 11
context = """
Das Makro `manylet` dupliziert den Ausdruck `e` syntaktisch als Bindung an jede
Variable links vom Gleichheitszeichen. Weil `s` aber ein String mit Ownership ist,
verschiebt die erste Bindung an `x` den Wert `s`, und die zweite Bindung an `y` ist ungültig.
"""

[[questions]]
id = "f4f664ef-4b0b-43ac-ba90-5051a4ef89fb"
type = "MultipleChoice"
prompt.prompt = """
Welche der folgenden Gründe sprechen dafür, ein Makro als
prozedurales statt als deklaratives Makro zu implementieren?
"""
answer.answer = [
    "Du willst dich in das derive-System von Rust einklinken",
    "Dein Makro erfordert eine nicht triviale Analyse der Syntax des Makro-Benutzers",
]
prompt.distractors = [
  "Du willst Codefolgen variabler Länge erzeugen",
  "Dein Makro braucht ein ganzes Element als Eingabe, nicht nur einen Ausdruck"
]
context = """
Prozedurale Makros sind die einzige Möglichkeit, ein benutzerdefiniertes derive zu erstellen. Prozedurale Makros
sind auch nützlich, wenn du Code brauchst, der die Syntax des Makro-Benutzers analysiert – deklarative
Makros erlauben nur, die Eingabe umzustellen, aber z. B. nicht, ihre Größe zu berechnen.

Deklarative Makros können Codefolgen variabler Länge erzeugen und können Elemente umhüllen/erzeugen,
nicht nur Ausdrücke.
"""

[[questions]]
id = "4c7dce03-99c6-41e3-8482-ccf4e30974ff"
type = "MultipleChoice"
prompt.prompt = """
Welche der folgenden Aussagen beschreibt die Eingabe eines prozeduralen Makros am besten?
"""
answer.answer = "Die Eingabe ist eine Folge von Tokens"
prompt.distractors = [
  "Die Eingabe ist ein typisierter Kontrollflussgraph",
   "Die Eingabe ist ein abstrakter Syntaxbaum",
  "Die Eingabe ist ein Byte-String"
]
context = """
Prozedurale Makros nehmen Token-Streams als Eingabe (und erzeugen sie als Ausgabe).
Mit Crates wie `syn` kannst du Tokens in Syntaxbäume umwandeln.
"""