[[questions]]
id = "f08ab588-1dca-438e-8108-a1b2410a4343"
type = "MultipleChoice"
prompt.prompt = """
Stell dir vor, du implementierst eine Funktion `register`, die einen Callback nimmt, auf zwei Arten:

```
fn register1(cb: fn(Event) -> ());
fn register2<F>(cb: F) where F: Fn(Event) -> ();
```

Welche Typsignatur erlaubt es `register`, die größte Vielfalt an Argumenten anzunehmen?
"""
answer.answer = "`register2`"
prompt.distractors = [
  "`register1`",
  "Beide sind gleichwertig"
]
context = """
An `register2` können Closures mit Umgebung übergeben werden, an `register1` dagegen nur Funktionen auf oberster Ebene (oder Closures ohne Umgebung).
"""