[[questions]]
id = "d172fc53-0220-4ff4-83c9-9c0a6834dd8e"
type = "MultipleChoice"
prompt.prompt = "Was ist 1 + 1? (Klick ruhig mal auf eine falsche Antwort.)"
answer.answer = "2"
prompt.distractors = [ "0", "-999", "11" ]
context = """
Eine Erklärung dieser Tatsache findest du in den *Principia Mathematica*.
"""